
# AI-Powered Career Guidance Platform
## Experiment 2: Question-to-Feature Mapping

### Aim
To establish a systematic mapping between assessment questions, answer formats, scoring methods, engineered features, and the machine learning dataset.

### Objectives
- Load and inspect the 120-question assessment questionnaire.
- Examine the existing data dictionary and dataset schemas.
- Identify suitable feature mappings for each question.
- Establish answer encoding and scoring requirements.
- Validate mappings before model development.

### Expected Outcome
A validated question-to-feature mapping specification that connects the assessment questionnaire with the machine learning pipeline.


### 1. Import Required Libraries

We use pandas for loading and inspecting tabular data, pathlib for managing file paths, and json for reading the data dictionary.

In [4]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
import openpyxl
import pandas as pd

print("openpyxl version:", openpyxl.__version__)

QUESTIONNAIRE_PATH = PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx"

questions_df = pd.read_excel(
    QUESTIONNAIRE_PATH,
    sheet_name="Questions Dataset",
    engine="openpyxl"
)

print("Questionnaire loaded successfully!")
print("Shape:", questions_df.shape)
display(questions_df.head())

openpyxl version: 3.1.5
Questionnaire loaded successfully!
Shape: (120, 8)

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Scoring_Method,Feature_Mapping,Purpose
0,Q001,Interest,How interested are you in writing scripts or c...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in core programming and logic
1,Q002,Interest,How interested are you in analyzing large data...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in data science and statisti...
2,Q003,Interest,How interested are you in finding vulnerabilit...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in cybersecurity and risk mi...
3,Q004,Interest,How interested are you in sketching out wirefr...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in UI/UX and user-centric de...
4,Q005,Interest,How interested are you in coordinating team me...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in business management and l...

In [1]:

from pathlib import Path
import json
import pandas as pd

PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

files = {
    "Questionnaire": PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx",
    "Data Dictionary": PROJECT_DIR / "data_dictionary.json",
    "Raw Dataset": PROJECT_DIR / "career_guidance_raw_synthetic.csv",
    "Processed Dataset": PROJECT_DIR / "career_guidance_processed.csv",
    "Training Dataset": PROJECT_DIR / "career_guidance_train.csv",
    "Testing Dataset": PROJECT_DIR / "career_guidance_test.csv",
    "Existing Mapping Notebook": PROJECT_DIR / "Questionnaire_Scoring_and_Feature_Mapping.ipynb",
}

for name, path in files.items():
    status = "FOUND" if path.exists() else "NOT FOUND"
    print(f"{name}: {status}")

Questionnaire: FOUND
Data Dictionary: FOUND
Raw Dataset: FOUND
Processed Dataset: FOUND
Training Dataset: FOUND
Testing Dataset: FOUND
Existing Mapping Notebook: FOUND


## 2. Inspect Existing Mapping and Dataset Schemas

This section examines the existing questionnaire mapping notebook, data dictionary, and dataset columns. The purpose is to understand the current implementation and prevent duplicate work or incompatible feature definitions.

In [2]:

# 1. Inspect the existing mapping notebook
existing_notebook = (
    PROJECT_DIR / "Questionnaire_Scoring_and_Feature_Mapping.ipynb"
)

with open(existing_notebook, "r", encoding="utf-8") as file:
    notebook_data = json.load(file)

print("EXISTING MAPPING NOTEBOOK")
print("=" * 60)

for index, cell in enumerate(notebook_data.get("cells", [])):
    cell_type = cell.get("cell_type", "unknown")
    source = "".join(cell.get("source", []))

    if source.strip():
        print(f"\nCell {index + 1} [{cell_type}]")
        print(source[:1200])
        if len(source) > 1200:
            print("... [remaining content omitted]")


# 2. Inspect the data dictionary
dictionary_path = PROJECT_DIR / "data_dictionary.json"

with open(dictionary_path, "r", encoding="utf-8") as file:
    data_dictionary = json.load(file)

print("\n\nDATA DICTIONARY")
print("=" * 60)
print(json.dumps(data_dictionary, indent=2)[:10000])


# 3. Inspect the actual dataset schemas
dataset_files = {
    "Raw Dataset": "career_guidance_raw_synthetic.csv",
    "Processed Dataset": "career_guidance_processed.csv",
    "Training Dataset": "career_guidance_train.csv",
    "Testing Dataset": "career_guidance_test.csv",
}

for dataset_name, filename in dataset_files.items():
    dataset_path = PROJECT_DIR / filename
    df = pd.read_csv(dataset_path)

    print(f"\n{dataset_name}")
    print("-" * 60)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("First 3 rows:")
    display(df.head(3))

EXISTING MAPPING NOTEBOOK
============================================================

Cell 1 [code]
from pathlib import Path
import pandas as pd
import json

# Search the current notebook folder and its subfolders
BASE_DIR = Path.cwd()

def find_file(filename):
    matches = list(BASE_DIR.rglob(filename))
    if matches:
        return matches[0]
    return None

QUESTIONNAIRE_PATH = find_file("AI_Career_Guidance_Questions.xlsx")
DATASET_PATH = find_file("career_guidance_processed.csv")
DICTIONARY_PATH = find_file("data_dictionary.json")

print("Notebook working directory:", BASE_DIR)
print("Questionnaire found:", QUESTIONNAIRE_PATH)
print("Processed dataset found:", DATASET_PATH)
print("Data dictionary found:", DICTIONARY_PATH)

# Stop if either essential file is missing
if QUESTIONNAIRE_PATH is None:
    raise FileNotFoundError(
        "AI_Career_Guidance_Questions.xlsx was not found. "
        "Place it in the project folder or update QUESTIONNAIRE_PATH."
    )

if DATASET_PATH is None:
    raise FileNotFoundError(
        "career_guidance_processed.csv was not found. "
        "Place it in the project folder or update DATASET_PATH."
    )

# Load questionnaire and dataset
excel_file = pd.ExcelFile(QUESTIONNAIRE_PATH)
print("\nAvailable questionnaire sheets:", excel_file.shee
... [remaining content omitted]


DATA DICTIONARY
============================================================
{
  "dataset_name": "Synthetic Career Guidance Assessment Dataset",
  "version": "1.0",
  "rows_raw_including_injected_duplicates": 2412,
  "rows_after_duplicate_removal": 2400,
  "columns": [
    {
      "name": "profile_id",
      "type": "identifier",
      "description": "Synthetic profile identifier; exclude from ML features."
    },
    {
      "name": "age_group",
      "type": "categorical",
      "description": "Broad age band; use cautiously and assess fairness."
    },
    {
      "name": "education_level",
      "type": "categorical",
      "description": "Educational background category."
    },
    {
      "name": "experience_stage",
      "type": "categorical",
      "description": "Current study/career stage."
    },
    {
      "name": "region_type",
      "type": "categorical",
      "description": "Broad region type; exclude if it creates geographic bias."
    },
    {
      "name": "interest_technology",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "interest_data",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "interest_problem_solving",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "interest_creativity",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "interest_people",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "interest_helping",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "aptitude_logical",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "aptitude_numerical",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "aptitude_verbal",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "aptitude_spatial",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "aptitude_critical_thinking",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "trait_openness",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "trait_conscientiousness",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "trait_extraversion",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "trait_agreeableness",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "trait_emotional_stability",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "skill_programming",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "skill_data_analysis",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "skill_research",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "skill_communication",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "skill_leadership",
      "type": "numeric_1_to_10_raw_or_0_to_1_processed",
      "description": "Synthetic assessment score."
    },
    {
      "name": "recommended_career_domain",
      "type": "target_label",
      "description": "Synthetic label generated from the career-profile template used to create the sample."
    }
  ],
  "important_limitation": "All records and labels are synthetic, generated for development/testing. They are not real professional records and cannot validate real-world career suitability."
}

Raw Dataset
------------------------------------------------------------
Shape: (2412, 27)
Columns: ['profile_id', 'age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']
First 3 rows:

,profile_id,age_group,education_level,experience_stage,region_type,interest_technology,interest_data,interest_problem_solving,interest_creativity,interest_people,...,trait_conscientiousness,trait_extraversion,trait_agreeableness,trait_emotional_stability,skill_programming,skill_data_analysis,skill_research,skill_communication,skill_leadership,recommended_career_domain
0,CG00001,15-18,B.Sc Mathematics,1-3 years,Rural,6.3,10.0,9.6,3.8,3.9,...,9.6,7.7,5.8,6.5,5.4,10.0,5.9,6.7,4.8,Data Science & Analytics
1,CG00002,15-18,B.Sc Mathematics,Student,Rural,5.4,9.9,6.6,6.7,7.7,...,6.8,4.8,8.9,8.0,6.9,7.9,6.4,6.2,7.4,Finance & Accounting
2,CG00003,31+,B.Tech Mechanical,Student,Rural,8.1,8.5,9.0,3.6,5.5,...,7.5,6.2,7.8,7.0,9.3,6.4,6.2,7.5,4.7,Engineering & Core Technology

Processed Dataset
------------------------------------------------------------
Shape: (2400, 27)
Columns: ['profile_id', 'age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']
First 3 rows:

,profile_id,age_group,education_level,experience_stage,region_type,interest_technology,interest_data,interest_problem_solving,interest_creativity,interest_people,...,trait_conscientiousness,trait_extraversion,trait_agreeableness,trait_emotional_stability,skill_programming,skill_data_analysis,skill_research,skill_communication,skill_leadership,recommended_career_domain
0,CG00001,15-18,B.Sc Mathematics,1-3 years,Rural,0.588889,1.000000,0.955556,0.311111,0.322222,...,0.955556,0.744444,0.533333,0.611111,0.488889,1.000000,0.544444,0.633333,0.422222,Data Science & Analytics
1,CG00002,15-18,B.Sc Mathematics,Student,Rural,0.488889,0.988889,0.622222,0.633333,0.744444,...,0.644444,0.422222,0.877778,0.777778,0.655556,0.766667,0.600000,0.577778,0.711111,Finance & Accounting
2,CG00003,31+,B.Tech Mechanical,Student,Rural,0.788889,0.833333,0.888889,0.288889,0.500000,...,0.722222,0.577778,0.755556,0.666667,0.922222,0.600000,0.577778,0.722222,0.411111,Engineering & Core Technology

Training Dataset
------------------------------------------------------------
Shape: (1920, 26)
Columns: ['age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']
First 3 rows:

,age_group,education_level,experience_stage,region_type,interest_technology,interest_data,interest_problem_solving,interest_creativity,interest_people,interest_helping,...,trait_conscientiousness,trait_extraversion,trait_agreeableness,trait_emotional_stability,skill_programming,skill_data_analysis,skill_research,skill_communication,skill_leadership,recommended_career_domain
0,15-18,B.Tech Civil,1-3 years,Rural,5.9,10.0,6.4,7.3,5.8,5.2,...,10.0,6.2,6.5,6.4,7.0,6.7,5.1,6.6,4.9,Engineering & Core Technology
1,15-18,M.Sc,Entry-level,Rural,7.1,8.0,7.7,6.8,9.4,5.6,...,6.6,9.4,6.8,4.8,6.4,10.0,4.2,6.5,7.3,Education & Research
2,31+,BFA,4+ years,Rural,5.6,6.4,4.9,10.0,6.9,3.5,...,7.1,9.4,7.5,4.7,6.9,5.4,4.9,10.0,9.0,UI/UX Design

Testing Dataset
------------------------------------------------------------
Shape: (480, 26)
Columns: ['age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']
First 3 rows:

,age_group,education_level,experience_stage,region_type,interest_technology,interest_data,interest_problem_solving,interest_creativity,interest_people,interest_helping,...,trait_conscientiousness,trait_extraversion,trait_agreeableness,trait_emotional_stability,skill_programming,skill_data_analysis,skill_research,skill_communication,skill_leadership,recommended_career_domain
0,15-18,B.Sc Biology,Student,Semi-urban,8.9,2.9,7.8,3.9,7.2,7.6,...,6.1,8.3,8.2,8.9,5.4,4.6,7.2,5.7,4.7,Healthcare & Life Sciences
1,23-30,B.Tech IT,1-3 years,Semi-urban,7.8,7.6,7.6,6.2,6.8,4.1,...,10.0,6.0,8.9,6.9,8.0,6.8,2.4,7.5,5.4,Software Development
2,15-18,B.Com,Student,Semi-urban,8.8,3.5,8.1,8.9,7.1,6.0,...,8.3,9.9,8.1,6.5,4.8,6.2,7.9,6.5,6.0,Digital Marketing


## 3. Questionnaire Structure and Existing Mapping Analysis

This section examines the questionnaire sections, answer formats, and current mapping implementation. We will identify which existing dataset features can be supported by the questions and which new features may be required.

In [5]:

# Load the questionnaire
QUESTIONNAIRE_PATH = PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx"

questions_df = pd.read_excel(
    QUESTIONNAIRE_PATH,
    sheet_name="Questions Dataset"
)

print("Questionnaire shape:", questions_df.shape)
print("\nQuestionnaire columns:")
print(questions_df.columns.tolist())

print("\nQuestions by section:")
display(
    questions_df.groupby("Section")
    .size()
    .reset_index(name="Question_Count")
)

print("\nQuestions by answer type:")
display(
    questions_df.groupby("Answer_Type")
    .size()
    .reset_index(name="Question_Count")
)

print("\nCurrent mapping and scoring completeness:")
for column in ["Scoring_Method", "Feature_Mapping"]:
    if column in questions_df.columns:
        filled = questions_df[column].notna() & (
            questions_df[column].astype(str).str.strip() != ""
        )
        print(f"{column}: {filled.sum()} / {len(questions_df)} completed")

print("\nSample questions:")
display(
    questions_df[
        [
            "Question_ID",
            "Section",
            "Question_Text",
            "Answer_Type",
            "Scoring_Method",
            "Feature_Mapping",
            "Purpose"
        ]
    ].head(15)
)

# Inspect the existing mapping notebook's cell structure
existing_notebook = (
    PROJECT_DIR / "Questionnaire_Scoring_and_Feature_Mapping.ipynb"
)

with open(existing_notebook, "r", encoding="utf-8") as file:
    existing_nb = json.load(file)

print("\nExisting mapping notebook cell summary:")
for i, cell in enumerate(existing_nb.get("cells", []), start=1):
    source = "".join(cell.get("source", []))
    print(
        f"Cell {i}: {cell['cell_type']} | "
        f"{len(source)} characters | "
        f"{source.strip().splitlines()[0][:100] if source.strip() else '(empty)'}"
    )

Questionnaire shape: (120, 8)

Questionnaire columns:
['Question_ID', 'Section', 'Question_Text', 'Answer_Type', 'Answer_Options', 'Scoring_Method', 'Feature_Mapping', 'Purpose']

Questions by section:

                          Section  Question_Count
0                        Aptitude              10
1  Education & Career Preferences              80
2                        Interest              10
3                     Personality              10
4                          Skills              10

Questions by answer type:

               Answer_Type  Question_Count
0    Agreement Scale (1-5)              10
1                 Dropdown               3
2                      MCQ              87
3       Rating scale (1-5)              10
4  Skill Scale (1-5 + N/A)              10

Current mapping and scoring completeness:
Scoring_Method: 0 / 120 completed
Feature_Mapping: 0 / 120 completed

Sample questions:

,Question_ID,Section,Question_Text,Answer_Type,Scoring_Method,Feature_Mapping,Purpose
0,Q001,Interest,How interested are you in writing scripts or c...,Rating scale (1-5),NaN,NaN,Measures interest in core programming and logic
1,Q002,Interest,How interested are you in analyzing large data...,Rating scale (1-5),NaN,NaN,Measures interest in data science and statisti...
2,Q003,Interest,How interested are you in finding vulnerabilit...,Rating scale (1-5),NaN,NaN,Measures interest in cybersecurity and risk mi...
3,Q004,Interest,How interested are you in sketching out wirefr...,Rating scale (1-5),NaN,NaN,Measures interest in UI/UX and user-centric de...
4,Q005,Interest,How interested are you in coordinating team me...,Rating scale (1-5),NaN,NaN,Measures interest in business management and l...
5,Q006,Interest,How interested are you in studying human anato...,Rating scale (1-5),NaN,NaN,Measures interest in healthcare and life sciences
6,Q007,Interest,How interested are you in explaining difficult...,Rating scale (1-5),NaN,NaN,"Measures interest in education, teaching, and ..."
7,Q008,Interest,How interested are you in analyzing search eng...,Rating scale (1-5),NaN,NaN,Measures interest in digital marketing and gro...
8,Q009,Interest,How interested are you in auditing financial r...,Rating scale (1-5),NaN,NaN,"Measures interest in finance, accounting, and ..."
9,Q010,Interest,How interested are you in designing physical m...,Rating scale (1-5),NaN,NaN,Measures interest in core engineering (mechani...
10,Q011,Aptitude,A project requires 3 developers to complete in...,MCQ,NaN,NaN,Measures quantitative reasoning and inverse pr...
11,Q012,Aptitude,"If all 'Servers' are 'Computers', and some 'Co...",MCQ,NaN,NaN,Measures logical deduction and syllogism
12,Q013,Aptitude,"A dataset has the values: 15, 18, 22, 27, 33. ...",MCQ,NaN,NaN,Measures numerical pattern recognition
13,Q014,Aptitude,"In a given code language, 'DATA' is written as...",MCQ,NaN,NaN,Measures cryptographic reasoning and lateral t...
14,Q015,Aptitude,You are analyzing a chart where Revenue is gro...,MCQ,NaN,NaN,Measures data interpretation and business logic

Existing mapping notebook cell summary:
Cell 1: code | 1503 characters | from pathlib import Path
Cell 2: code | 0 characters | (empty)
Cell 3: code | 0 characters | (empty)

In [4]:

QUESTIONNAIRE_PATH = PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx"

if not QUESTIONNAIRE_PATH.exists():
    raise FileNotFoundError(
        f"Questionnaire not found: {QUESTIONNAIRE_PATH}"
    )

questions_df = pd.read_excel(
    QUESTIONNAIRE_PATH,
    sheet_name="Questions Dataset",
    engine="openpyxl"
)

print("Questionnaire loaded successfully!")
print("Dataset shape:", questions_df.shape)
display(questions_df.head())

Questionnaire loaded successfully!
Dataset shape: (120, 8)

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Scoring_Method,Feature_Mapping,Purpose
0,Q001,Interest,How interested are you in writing scripts or c...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in core programming and logic
1,Q002,Interest,How interested are you in analyzing large data...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in data science and statisti...
2,Q003,Interest,How interested are you in finding vulnerabilit...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in cybersecurity and risk mi...
3,Q004,Interest,How interested are you in sketching out wirefr...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in UI/UX and user-centric de...
4,Q005,Interest,How interested are you in coordinating team me...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in business management and l...

In [3]:

from pathlib import Path
import pandas as pd
import json
import openpyxl

# Define project directory
PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

# Load questionnaire
QUESTIONNAIRE_PATH = PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx"

if not PROJECT_DIR.exists():
    raise FileNotFoundError(f"Project folder not found: {PROJECT_DIR}")

if not QUESTIONNAIRE_PATH.exists():
    raise FileNotFoundError(f"Excel file not found: {QUESTIONNAIRE_PATH}")

questions_df = pd.read_excel(
    QUESTIONNAIRE_PATH,
    sheet_name="Questions Dataset",
    engine="openpyxl"
)

print("Project directory verified.")
print("Questionnaire loaded successfully!")
print("Shape:", questions_df.shape)
print("\nColumns:")
print(questions_df.columns.tolist())

display(questions_df.head())

Project directory verified.
Questionnaire loaded successfully!
Shape: (120, 8)

Columns:
['Question_ID', 'Section', 'Question_Text', 'Answer_Type', 'Answer_Options', 'Scoring_Method', 'Feature_Mapping', 'Purpose']

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Scoring_Method,Feature_Mapping,Purpose
0,Q001,Interest,How interested are you in writing scripts or c...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in core programming and logic
1,Q002,Interest,How interested are you in analyzing large data...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in data science and statisti...
2,Q003,Interest,How interested are you in finding vulnerabilit...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in cybersecurity and risk mi...
3,Q004,Interest,How interested are you in sketching out wirefr...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in UI/UX and user-centric de...
4,Q005,Interest,How interested are you in coordinating team me...,Rating scale (1-5),1 - Not interested at all to 5 - Extremely int...,NaN,NaN,Measures interest in business management and l...


## 4. Questionnaire Structure Analysis

This section analyzes the distribution of questions across assessment sections and answer formats. Understanding these distributions helps us determine appropriate encoding, scoring, and feature-mapping strategies for each question type.

In [6]:

# Analyze questions by section
print("QUESTION DISTRIBUTION BY SECTION")
section_summary = (
    questions_df.groupby("Section")
    .size()
    .reset_index(name="Question_Count")
    .sort_values("Section")
)
display(section_summary)

# Analyze questions by answer type
print("\nQUESTION DISTRIBUTION BY ANSWER TYPE")
answer_summary = (
    questions_df.groupby("Answer_Type")
    .size()
    .reset_index(name="Question_Count")
    .sort_values("Answer_Type")
)
display(answer_summary)

# Check scoring and feature mapping completeness
print("\nSCORING AND MAPPING COMPLETENESS")

for column in ["Scoring_Method", "Feature_Mapping"]:
    filled = (
        questions_df[column].notna()
        & questions_df[column].astype(str).str.strip().ne("")
    )
    print(f"{column}: {filled.sum()} / {len(questions_df)} populated")

# Check duplicate question IDs
print("\nDUPLICATE QUESTION IDs:", questions_df["Question_ID"].duplicated().sum())

# Check missing values
print("\nMISSING VALUES")
display(questions_df.isna().sum().rename("Missing_Count").to_frame())

# Review all question IDs and purposes
print("\nQUESTION INVENTORY")
display(
    questions_df[
        ["Question_ID", "Section", "Answer_Type", "Purpose"]
    ]
)

QUESTION DISTRIBUTION BY SECTION

                          Section  Question_Count
0                        Aptitude              10
1  Education & Career Preferences              80
2                        Interest              10
3                     Personality              10
4                          Skills              10

QUESTION DISTRIBUTION BY ANSWER TYPE

               Answer_Type  Question_Count
0    Agreement Scale (1-5)              10
1                 Dropdown               3
2                      MCQ              87
3       Rating scale (1-5)              10
4  Skill Scale (1-5 + N/A)              10

SCORING AND MAPPING COMPLETENESS
Scoring_Method: 0 / 120 populated
Feature_Mapping: 0 / 120 populated

DUPLICATE QUESTION IDs: 0

MISSING VALUES

                 Missing_Count
Question_ID                  0
Section                      0
Question_Text                0
Answer_Type                  0
Answer_Options               0
Scoring_Method             120
Feature_Mapping            120
Purpose                      0

QUESTION INVENTORY

,Question_ID,Section,Answer_Type,Purpose
0,Q001,Interest,Rating scale (1-5),Measures interest in core programming and logic
1,Q002,Interest,Rating scale (1-5),Measures interest in data science and statisti...
2,Q003,Interest,Rating scale (1-5),Measures interest in cybersecurity and risk mi...
3,Q004,Interest,Rating scale (1-5),Measures interest in UI/UX and user-centric de...
4,Q005,Interest,Rating scale (1-5),Measures interest in business management and l...
...,...,...,...,...
115,Q116,Education & Career Preferences,MCQ,Domain Preference: Law & Public Service
116,Q117,Education & Career Preferences,MCQ,Domain Preference: Law & Public Service
117,Q118,Education & Career Preferences,MCQ,Domain Preference: Law & Public Service
118,Q119,Education & Career Preferences,MCQ,Domain Preference: Law & Public Service
119,Q120,Education & Career Preferences,MCQ,Domain Preference: Law & Public Service


## 5. Existing Dataset Feature Compatibility Analysis

The current dataset contains predefined interest, aptitude, personality, and skill features, along with educational background and the target career domain.

This section compares these existing columns with the questionnaire design. It identifies which dimensions already exist and which question groups require additional scoring rules, feature engineering, or separate preference handling.

No scoring rules or dataset columns will be modified in this step.

In [7]:

# Load the existing dataset and data dictionary
PROCESSED_PATH = PROJECT_DIR / "career_guidance_processed.csv"
DICTIONARY_PATH = PROJECT_DIR / "data_dictionary.json"

processed_df = pd.read_csv(PROCESSED_PATH)

with open(DICTIONARY_PATH, "r", encoding="utf-8") as file:
    data_dictionary = json.load(file)

# Display current dataset features
existing_columns = processed_df.columns.tolist()

print("EXISTING DATASET COLUMNS")
print("=" * 60)

for column in existing_columns:
    print(column)

# Identify the target and identifier
print("\nTARGET AND IDENTIFIER")
print("=" * 60)
print("Target:", "recommended_career_domain")
print("Identifier:", "profile_id")

# Summarize the current assessment dimensions
feature_groups = {
    "Interest": [
        "interest_technology", "interest_data",
        "interest_problem_solving", "interest_creativity",
        "interest_people", "interest_helping"
    ],
    "Aptitude": [
        "aptitude_logical", "aptitude_numerical",
        "aptitude_verbal", "aptitude_spatial",
        "aptitude_critical_thinking"
    ],
    "Personality": [
        "trait_openness", "trait_conscientiousness",
        "trait_extraversion", "trait_agreeableness",
        "trait_emotional_stability"
    ],
    "Skills": [
        "skill_programming", "skill_data_analysis",
        "skill_research", "skill_communication",
        "skill_leadership"
    ]
}

print("\nEXISTING ASSESSMENT DIMENSIONS")
print("=" * 60)

for group, features in feature_groups.items():
    available = [f for f in features if f in existing_columns]
    print(f"\n{group}: {len(available)}/{len(features)} features found")
    print(available)

# Review all career preference questions
print("\nCAREER PREFERENCE QUESTIONS (Q041-Q120)")
print("=" * 60)

career_questions = questions_df[
    questions_df["Question_ID"].str.match(r"Q0(4[1-9]|[5-9][0-9])|Q1[01][0-9]|Q120")
].copy()

display(
    career_questions[
        [
            "Question_ID", "Question_Text",
            "Answer_Type", "Answer_Options", "Purpose"
        ]
    ].to_string(index=False)
)

# Show the target career domains present in the dataset
print("\nEXISTING TARGET LABELS")
print("=" * 60)

display(
    processed_df["recommended_career_domain"]
    .value_counts()
    .rename_axis("Career_Domain")
    .reset_index(name="Record_Count")
)

EXISTING DATASET COLUMNS
============================================================
profile_id
age_group
education_level
experience_stage
region_type
interest_technology
interest_data
interest_problem_solving
interest_creativity
interest_people
interest_helping
aptitude_logical
aptitude_numerical
aptitude_verbal
aptitude_spatial
aptitude_critical_thinking
trait_openness
trait_conscientiousness
trait_extraversion
trait_agreeableness
trait_emotional_stability
skill_programming
skill_data_analysis
skill_research
skill_communication
skill_leadership
recommended_career_domain

TARGET AND IDENTIFIER
============================================================
Target: recommended_career_domain
Identifier: profile_id

EXISTING ASSESSMENT DIMENSIONS
============================================================

Interest: 6/6 features found
['interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping']

Aptitude: 5/5 features found
['aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking']

Personality: 5/5 features found
['trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability']

Skills: 5/5 features found
['skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership']

CAREER PREFERENCE QUESTIONS (Q041-Q120)
============================================================

"Question_ID                                                                                                        Question_Text Answer_Type                                                                                    Answer_Options                                  Purpose\n       Q041                                                  What is your current or most recently completed level of education?    Dropdown                                            High School, Diploma, Bachelor's, Master's, PhD, Other                        General Education\n       Q042                                     Which broad academic field does your primary degree or certification fall under?    Dropdown                                  Engineering, Business, Arts, Sciences, Medicine, Law, None/Other                        General Education\n       Q043                                                         What is your cumulative academic performance/GPA equivalent?         MCQ                                       Top 10%, Top 25%, Average, Below Average, Prefer not to say                        General Education\n       Q044               Have you completed any specialized bootcamps or professional certifications outside of formal degrees?         MCQ                                                          Yes - Technical, Yes - Non-Technical, No                        General Education\n       Q045                     How many total years of formal education/training do you have in your primary field of interest?         MCQ                                                           <1 year, 1-3 years, 3-5 years, 5+ years                        General Education\n       Q046                                      How many years of full-time professional work experience do you currently have?         MCQ                                                                               0, <1, 1-3, 3-5, 5+                       General Experience\n       Q047                                Have you ever completed an internship, apprenticeship, or practical training program?         MCQ                                                                                           Yes, No                       General Experience\n       Q048                            Have you ever held a leadership or management role where you were responsible for others?         MCQ                                                                                           Yes, No                       General Experience\n       Q049                                 Do you have experience working as a freelancer or running your own business/startup?         MCQ                                                                                           Yes, No                       General Experience\n       Q050                                                     What is the largest team size you have consistently worked with?         MCQ                                                                              Solo, 2-5, 6-15, 15+                       General Experience\n       Q051                                                                              What is your primary career motivation?         MCQ                     High Salary, Work-Life Balance, Social Impact, Innovation/Building, Stability                             Career Goals\n       Q052                           What is your minimum acceptable starting salary expectation (in your local currency/tier)?    Dropdown                                                                         [List of standard ranges]                             Career Goals\n       Q053                         Are you willing to relocate to a different city or country for the right career opportunity?         MCQ                                                                    Yes, No, Only within my region                             Career Goals\n       Q054                                                                                Where do you see yourself in 5 years?         MCQ                  Individual Contributor/Expert, Manager/Leader, Entrepreneur, Academic/Researcher                             Career Goals\n       Q055                              How important is job security and stability compared to rapid, high-risk career growth?         MCQ                              Highly prefer stability, Balance of both, Highly prefer rapid growth                             Career Goals\n       Q056                                                                          What is your preferred working environment?         MCQ                                                                 100% Remote, Hybrid, 100% On-site                    Preferred Environment\n       Q057                                                                        Which company size do you prefer working for?         MCQ Early-stage Startup, Mid-size Enterprise, Large Multinational Corporate, Government/Public Sector                    Preferred Environment\n       Q058                                           Are you willing to travel frequently (more than 30% of the time) for work?         MCQ                                                                             Yes, No, Occasionally                    Preferred Environment\n       Q059           Do you prefer a predictable 9-to-5 schedule or flexible hours that may require occasional nights/weekends?         MCQ                                                             Strict 9-5, Flexible/Results-oriented                    Preferred Environment\n       Q060                                                                           How do you prefer to be evaluated at work?         MCQ                 By measurable data/KPIs, By project completion/portfolio, By peer/manager reviews                    Preferred Environment\n       Q061                                                         Which aspect of software development interests you the most?         MCQ                                            Frontend/UI, Backend/Server, Mobile Apps, Architecture  Domain Preference: Software Development\n       Q062                                    Are you willing to participate in on-call rotations for emergency system outages?         MCQ                                                                                   Yes, No, Unsure  Domain Preference: Software Development\n       Q063                                    Do you prefer building consumer-facing applications or internal enterprise tools?         MCQ                                                    Consumer-facing, Internal tools, No preference  Domain Preference: Software Development\n       Q064                                     How comfortable are you with continuous integration and rapid deployment cycles?         MCQ                                Very comfortable, Somewhat, Prefer slower releases, Not applicable  Domain Preference: Software Development\n       Q065                                                                   Which software ecosystem do you prefer working in?         MCQ                                      Open Source/Linux, Microsoft/Enterprise, Apple/iOS, Agnostic  Domain Preference: Software Development\n       Q066       Do you prefer building predictive machine learning models or creating dashboards/reports for business leaders?         MCQ                                                               ML Models, Dashboards, Both equally          Domain Preference: Data Science\n       Q067                              Are you comfortable dealing with messy, unstructured data that requires heavy cleaning?         MCQ                                                                                   Yes, No, Unsure          Domain Preference: Data Science\n       Q068          Do you prefer deep-diving into a single complex algorithm or applying multiple standard algorithms rapidly?         MCQ                                                                      Deep dive, Rapid application          Domain Preference: Data Science\n       Q069                 How important is it for you to work with cutting-edge AI technologies (e.g., LLMs, Computer Vision)?         MCQ                                                            Mandatory, Nice to have, Not important          Domain Preference: Data Science\n       Q070                           Are you comfortable presenting complex statistical findings to non-technical stakeholders?         MCQ                                                                                   Yes, No, Unsure          Domain Preference: Data Science\n       Q071 Do you prefer offensive security (Red Team/Penetration Testing) or defensive security (Blue Team/Incident Response)?         MCQ                                                                 Offensive, Defensive, Both/Purple         Domain Preference: Cybersecurity\n       Q072                  Are you willing to undergo extensive background checks and maintain government security clearances?         MCQ                                                                                           Yes, No         Domain Preference: Cybersecurity\n       Q073                           How comfortable are you working in high-stress, time-critical incident response scenarios?         MCQ                                                     Very comfortable, Somewhat, Prefer low-stress         Domain Preference: Cybersecurity\n       Q074                   Do you prefer auditing policies and compliance, or actively hunting for technical vulnerabilities?         MCQ                                                              Compliance/Policy, Technical Hunting         Domain Preference: Cybersecurity\n       Q075                              Are you willing to continually study new threat vectors outside of standard work hours?         MCQ                                                                                           Yes, No         Domain Preference: Cybersecurity\n       Q076               Do you prefer conducting user research (interviews, surveys) or creating high-fidelity visual designs?         MCQ                                                        User Research, Visual Design, Both equally          Domain Preference: UI/UX Design\n       Q077                 How comfortable are you adapting your designs based on strict technical limitations from developers?         MCQ                                                           Very comfortable, Somewhat, Frustrating          Domain Preference: UI/UX Design\n       Q078                     Do you prefer working on entirely new product concepts or optimizing existing legacy interfaces?         MCQ                                                                 New concepts, Optimizing existing          Domain Preference: UI/UX Design\n       Q079                     How important is establishing and maintaining a strict design system (component library) to you?         MCQ                                                    Very important, Somewhat, Prefer ad-hoc design          Domain Preference: UI/UX Design\n       Q080                            Are you comfortable defending your design choices to stakeholders using qualitative data?         MCQ                                                                                           Yes, No          Domain Preference: UI/UX Design\n       Q081                       Do you prefer managing people (HR, team dynamics) or managing processes (Agile, supply chain)?         MCQ                                                                           People, Processes, Both Domain Preference: Business & Management\n       Q082                       How comfortable are you taking responsibility for a project's financial profit and loss (P&L)?         MCQ                                                       Very comfortable, Somewhat, Prefer to avoid Domain Preference: Business & Management\n       Q083                    Do you prefer strategizing long-term corporate visions or executing short-term operational goals?         MCQ                                                          Long-term strategy, Short-term execution Domain Preference: Business & Management\n       Q084                       Are you comfortable resolving interpersonal conflicts between team members on a regular basis?         MCQ                                                                                           Yes, No Domain Preference: Business & Management\n       Q085                                   How important is having a clear, hierarchical path to executive leadership to you?         MCQ                                                       Very important, Nice to have, Not important Domain Preference: Business & Management\n       Q086      Do you prefer interacting directly with patients or working behind the scenes in a laboratory/research setting?         MCQ                                                          Direct patient care, Laboratory/Research            Domain Preference: Healthcare\n       Q087                   How comfortable are you dealing with bodily fluids, severe illnesses, or emergency medical trauma?         MCQ                                                                Comfortable, Uncomfortable, Unsure            Domain Preference: Healthcare\n       Q088                                  Are you willing to work irregular shifts, including nights, weekends, and holidays?         MCQ                                                                        Yes, No, Only if necessary            Domain Preference: Healthcare\n       Q089                                                              Do you prefer clinical practice or biomedical research?         MCQ                                                                                Clinical, Research            Domain Preference: Healthcare\n       Q090               How comfortable are you navigating strict healthcare regulations and medical documentation procedures?         MCQ                                                       Very comfortable, Somewhat, Prefer to avoid            Domain Preference: Healthcare\n       Q091                                     What age group do you most prefer teaching or designing educational content for?         MCQ                                      Early Childhood, K-12, Higher Ed/University, Adult/Corporate  Domain Preference: Education & Research\n       Q092                                     Do you prefer lecturing in front of large groups or providing 1-on-1 mentorship?         MCQ                                                                Large groups, 1-on-1, Both equally  Domain Preference: Education & Research\n       Q093                                      How important is tenure or long-term academic job security to your career plan?         MCQ                                                           Very important, Somewhat, Not important  Domain Preference: Education & Research\n       Q094                  Do you prefer focusing on pedagogy (how to teach) or deep subject-matter expertise (what to teach)?         MCQ                                                                          Pedagogy, Subject Matter  Domain Preference: Education & Research\n       Q095          Are you comfortable dedicating significant time to grading, curriculum planning, and administrative duties?         MCQ                                                                                           Yes, No  Domain Preference: Education & Research\n       Q096                                                           Do you prefer data-driven marketing or creative marketing?         MCQ                                                                       Data-driven, Creative, Both     Domain Preference: Digital Marketing\n       Q097                               How comfortable are you pivoting campaigns rapidly based on daily social media trends?         MCQ                                              Very comfortable, Prefer long-term planned campaigns     Domain Preference: Digital Marketing\n       Q098                                                                     Do you prefer B2B or B2C marketing environments?         MCQ                                                                           B2B, B2C, No preference     Domain Preference: Digital Marketing\n       Q099                         Are you comfortable managing large advertising budgets where ROI must be strictly justified?         MCQ                                                                                           Yes, No     Domain Preference: Digital Marketing\n       Q100                     How important is public visibility (e.g., managing influencer relations, PR) in your ideal role?         MCQ                                                Very important, Somewhat, Prefer behind the scenes     Domain Preference: Digital Marketing\n       Q101                                                            Do you prefer corporate accounting or investment finance?         MCQ                                                                    Accounting, Investment Finance  Domain Preference: Finance & Accounting\n       Q102                      How comfortable are you making high-stakes financial decisions based on incomplete market data?         MCQ                                           Very comfortable, Prefer having all data, Uncomfortable  Domain Preference: Finance & Accounting\n       Q103                                     Are you willing to work extremely long hours during tax season or deal closures?         MCQ                                                                        Yes, No, Only occasionally  Domain Preference: Finance & Accounting\n       Q104                                                 Do you prefer client-facing advisory roles or quantitative analysis?         MCQ                                                                   Advisory, Quantitative Analysis  Domain Preference: Finance & Accounting\n       Q105                    How important is obtaining prestigious certifications (e.g., CPA, CFA) to your career trajectory?         MCQ                                                            Mandatory, Nice to have, Not necessary  Domain Preference: Finance & Accounting\n       Q106                                                   Which branch of core engineering aligns closest to your interests?         MCQ               Mechanical/Automotive, Civil/Structural, Electrical/Electronics, Chemical/Materials    Domain Preference: Engineering & Tech\n       Q107                     Do you prefer hands-on fieldwork/manufacturing floors or office-based CAD design and simulation?         MCQ                                                       Fieldwork/Hands-on, Office/CAD, Mix of both    Domain Preference: Engineering & Tech\n       Q108                                     How comfortable are you adhering to strict safety protocols and municipal codes?         MCQ                                                 Very comfortable, Somewhat, Find them restrictive    Domain Preference: Engineering & Tech\n       Q109                                       Are you willing to be deployed to remote industrial sites for weeks at a time?         MCQ                                                                                           Yes, No    Domain Preference: Engineering & Tech\n       Q110                  Do you prefer maintaining and optimizing existing infrastructure or designing entirely new systems?         MCQ                                                             Maintaining/Optimizing, Designing new    Domain Preference: Engineering & Tech\n       Q111                                     

EXISTING TARGET LABELS
============================================================

                    Career_Domain  Record_Count
0                    UI/UX Design           211
1            Law & Public Service           208
2            Education & Research           207
3      Healthcare & Life Sciences           207
4            Software Development           205
5        Data Science & Analytics           201
6   Engineering & Core Technology           200
7           Business & Management           200
8               Digital Marketing           196
9            Finance & Accounting           189
10          Creative Arts & Media           189
11                  Cybersecurity           187


## 6. Draft Question-to-Feature Mapping

This section creates an initial mapping specification for all 120 questions. It records the question category, response type, proposed feature role, and mapping status.

The mapping is a draft. Scoring rules and target-label alignment must be validated before the specification is used to transform real user responses or train the final recommendation model.

In [8]:

# Create a draft mapping table without modifying the source questionnaire

def classify_question(row):
    qid = row["Question_ID"]
    section = row["Section"]
    answer_type = row["Answer_Type"]

    if qid <= "Q010" and section == "Interest":
        role = "Assessment feature"
        status = "Needs semantic feature mapping"

    elif section == "Aptitude":
        role = "Assessment feature"
        status = "Needs answer-key and scoring validation"

    elif section == "Personality":
        role = "Assessment feature"
        status = "Needs trait scoring validation"

    elif section == "Skills":
        role = "Assessment feature"
        status = "Needs skill scoring and N/A handling"

    elif qid >= "Q061":
        role = "Career preference"
        status = "Needs domain-preference encoding"

    else:
        role = "Context or constraint"
        status = "Needs encoding and recommendation-role review"

    return pd.Series({
        "Proposed_Role": role,
        "Mapping_Status": status,
        "Answer_Type": answer_type
    })


mapping_df = questions_df.copy()

classification = mapping_df.apply(classify_question, axis=1)
mapping_df["Proposed_Role"] = classification["Proposed_Role"]
mapping_df["Mapping_Status"] = classification["Mapping_Status"]

# Add empty columns for decisions that require further validation
mapping_df["Proposed_Feature"] = pd.NA
mapping_df["Proposed_Scoring_Method"] = pd.NA
mapping_df["Encoding_Method"] = pd.NA

# Display a summary of the draft
print("Draft mapping created.")
print("Total questions:", len(mapping_df))

print("\nQuestions by proposed role:")
display(
    mapping_df["Proposed_Role"]
    .value_counts()
    .rename_axis("Proposed_Role")
    .reset_index(name="Question_Count")
)

print("\nSample mapping rows:")
display(
    mapping_df[
        [
            "Question_ID",
            "Section",
            "Answer_Type",
            "Proposed_Role",
            "Proposed_Feature",
            "Proposed_Scoring_Method",
            "Mapping_Status"
        ]
    ].head(20)
)

Draft mapping created.
Total questions: 120

Questions by proposed role:

           Proposed_Role  Question_Count
0      Career preference              60
1     Assessment feature              40
2  Context or constraint              20

Sample mapping rows:

,Question_ID,Section,Answer_Type,Proposed_Role,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
0,Q001,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
1,Q002,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
2,Q003,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
3,Q004,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
4,Q005,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
5,Q006,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
6,Q007,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
7,Q008,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
8,Q009,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
9,Q010,Interest,Rating scale (1-5),Assessment feature,<NA>,<NA>,Needs semantic feature mapping
10,Q011,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
11,Q012,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
12,Q013,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
13,Q014,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
14,Q015,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
15,Q016,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
16,Q017,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
17,Q018,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
18,Q019,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation
19,Q020,Aptitude,MCQ,Assessment feature,<NA>,<NA>,Needs answer-key and scoring validation

### Step 7 — Define Question-to-Feature Mapping

**Objective:** Map questionnaire responses to the existing ML dataset features wherever the relationship is meaningful.

**Approach:**
1. Map Interest, Personality, and Skills questions to their corresponding feature columns.
2. Map Aptitude MCQs to aptitude dimensions, pending answer-key validation.
3. Identify career-preference questions that will support career-domain matching.
4. Identify context questions that will be used as recommendation filters or supporting information.
5. Mark mappings requiring validation instead of assigning unsupported scores.

**Important:** The existing dataset is synthetic. Mapping questionnaire questions to its columns does not prove that the dataset's scores were generated from those questionnaire responses.

In [9]:

# Step 7: Define existing ML features and inspect question mappings

feature_groups = {
    "Interest": [
        "interest_technology",
        "interest_data",
        "interest_problem_solving",
        "interest_creativity",
        "interest_people",
        "interest_helping",
    ],
    "Aptitude": [
        "aptitude_logical",
        "aptitude_numerical",
        "aptitude_verbal",
        "aptitude_spatial",
        "aptitude_critical_thinking",
    ],
    "Personality": [
        "trait_openness",
        "trait_conscientiousness",
        "trait_extraversion",
        "trait_agreeableness",
        "trait_emotional_stability",
    ],
    "Skills": [
        "skill_programming",
        "skill_data_analysis",
        "skill_research",
        "skill_communication",
        "skill_leadership",
    ],
}

# Confirm the expected ML feature columns exist in the processed dataset.
processed_path = PROJECT_DIR / "career_guidance_processed.csv"
processed_df = pd.read_csv(processed_path)

available_columns = set(processed_df.columns)

feature_check = pd.DataFrame([
    {
        "Section": section,
        "Feature": feature,
        "Exists_In_Dataset": feature in available_columns,
    }
    for section, features in feature_groups.items()
    for feature in features
])

display(feature_check)

print("\nFeature columns missing from the dataset:")
display(feature_check.loc[~feature_check["Exists_In_Dataset"]])

# Inspect the actual wording before assigning question-level mappings.
for section in ["Interest", "Aptitude", "Personality", "Skills"]:
    print(f"\n--- {section} questions ---")
    display(
        questions_df.loc[
            questions_df["Section"].eq(section),
            ["Question_ID", "Question_Text", "Answer_Type", "Purpose"],
        ].reset_index(drop=True)
    )

        Section                     Feature  Exists_In_Dataset
0      Interest         interest_technology               True
1      Interest               interest_data               True
2      Interest    interest_problem_solving               True
3      Interest         interest_creativity               True
4      Interest             interest_people               True
5      Interest            interest_helping               True
6      Aptitude            aptitude_logical               True
7      Aptitude          aptitude_numerical               True
8      Aptitude             aptitude_verbal               True
9      Aptitude            aptitude_spatial               True
10     Aptitude  aptitude_critical_thinking               True
11  Personality              trait_openness               True
12  Personality     trait_conscientiousness               True
13  Personality          trait_extraversion               True
14  Personality         trait_agreeableness               True
15  Personality   trait_emotional_stability               True
16       Skills           skill_programming               True
17       Skills         skill_data_analysis               True
18       Skills              skill_research               True
19       Skills         skill_communication               True
20       Skills            skill_leadership               True

Feature columns missing from the dataset:

Empty DataFrame
Columns: [Section, Feature, Exists_In_Dataset]
Index: []

--- Interest questions ---

,Question_ID,Question_Text,Answer_Type,Purpose
0,Q001,How interested are you in writing scripts or c...,Rating scale (1-5),Measures interest in core programming and logic
1,Q002,How interested are you in analyzing large data...,Rating scale (1-5),Measures interest in data science and statisti...
2,Q003,How interested are you in finding vulnerabilit...,Rating scale (1-5),Measures interest in cybersecurity and risk mi...
3,Q004,How interested are you in sketching out wirefr...,Rating scale (1-5),Measures interest in UI/UX and user-centric de...
4,Q005,How interested are you in coordinating team me...,Rating scale (1-5),Measures interest in business management and l...
5,Q006,How interested are you in studying human anato...,Rating scale (1-5),Measures interest in healthcare and life sciences
6,Q007,How interested are you in explaining difficult...,Rating scale (1-5),"Measures interest in education, teaching, and ..."
7,Q008,How interested are you in analyzing search eng...,Rating scale (1-5),Measures interest in digital marketing and gro...
8,Q009,How interested are you in auditing financial r...,Rating scale (1-5),"Measures interest in finance, accounting, and ..."
9,Q010,How interested are you in designing physical m...,Rating scale (1-5),Measures interest in core engineering (mechani...

--- Aptitude questions ---

,Question_ID,Question_Text,Answer_Type,Purpose
0,Q011,A project requires 3 developers to complete in...,MCQ,Measures quantitative reasoning and inverse pr...
1,Q012,"If all 'Servers' are 'Computers', and some 'Co...",MCQ,Measures logical deduction and syllogism
2,Q013,"A dataset has the values: 15, 18, 22, 27, 33. ...",MCQ,Measures numerical pattern recognition
3,Q014,"In a given code language, 'DATA' is written as...",MCQ,Measures cryptographic reasoning and lateral t...
4,Q015,You are analyzing a chart where Revenue is gro...,MCQ,Measures data interpretation and business logic
5,Q016,An algorithm processes an array of n elements ...,MCQ,Measures algorithmic thinking and computationa...
6,Q017,If a machine produces 5 widgets every 20 minut...,MCQ,Measures algebraic problem solving
7,Q018,Evaluate the argument: 'Since the new UI was l...,MCQ,Measures critical reasoning and analytical thi...
8,Q019,"You have three boxes labeled 'Apples', 'Orange...",MCQ,Measures complex problem solving and constrain...
9,Q020,A plane is flying against a headwind of 50 mph...,MCQ,Measures applied mathematics and kinematics

--- Personality questions ---

,Question_ID,Question_Text,Answer_Type,Purpose
0,Q021,I thrive in environments where I must collabor...,Agreement Scale (1-5),Measures teamwork vs. independent work preference
1,Q022,I prefer structured environments with clear gu...,Agreement Scale (1-5),Measures adaptability and comfort with ambiguity
2,Q023,I naturally take charge of situations and enjo...,Agreement Scale (1-5),Measures leadership propensity
3,Q024,I am highly detail-oriented and will spend ext...,Agreement Scale (1-5),Measures conscientiousness and attention to de...
4,Q025,I actively seek out opportunities to learn ent...,Agreement Scale (1-5),Measures openness to experience and intellectu...
5,Q026,I perform well under tight deadlines and high-...,Agreement Scale (1-5),Measures emotional stability and stress tolerance
6,Q027,I prefer to follow established rules and proto...,Agreement Scale (1-5),Measures rule adherence vs. disruptive innovation
7,Q028,"I enjoy engaging with clients, customers, or t...",Agreement Scale (1-5),Measures extroversion and social interaction p...
8,Q029,I tend to rely on logical analysis and objecti...,Agreement Scale (1-5),Measures analytical thinking vs. intuitive fee...
9,Q030,I am comfortable abandoning a project I've wor...,Agreement Scale (1-5),Measures adaptability and lack of sunk-cost bias

--- Skills questions ---

,Question_ID,Question_Text,Answer_Type,Purpose
0,Q031,"How would you rate your ability to write, debu...",Skill Scale (1-5 + N/A),Measures software development capability
1,Q032,How would you rate your ability to use tools l...,Skill Scale (1-5 + N/A),Measures data analytics capability
2,Q033,How would you rate your proficiency with desig...,Skill Scale (1-5 + N/A),Measures UI/UX and graphic design capability
3,Q034,How would you rate your ability to read financ...,Skill Scale (1-5 + N/A),Measures finance and accounting capability
4,Q035,How would you rate your ability to configure f...,Skill Scale (1-5 + N/A),Measures cybersecurity capability
5,Q036,"How would you rate your ability to plan, execu...",Skill Scale (1-5 + N/A),Measures project management capability
6,Q037,How would you rate your ability to set up targ...,Skill Scale (1-5 + N/A),Measures digital marketing capability
7,Q038,How would you rate your ability to comprehend ...,Skill Scale (1-5 + N/A),Measures legal and policy capability
8,Q039,How would you rate your proficiency with core ...,Skill Scale (1-5 + N/A),Measures core engineering capability
9,Q040,How would you rate your ability to conduct aca...,Skill Scale (1-5 + N/A),Measures academic and scientific research capa...

## Step 8A — Finalize the mapping for Q001–Q040

In [12]:

# Step 8A: Consolidate question mappings Q001-Q040
# Self-contained version: does not depend on feature_mapping
# or aptitude_answer_key variables from previous cells.

import pandas as pd

# Ensure the questionnaire is loaded.
if "questions_df" not in globals():
    from pathlib import Path

    PROJECT_DIR = Path(
        r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
    )

    questions_df = pd.read_excel(
        PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx",
        sheet_name="Questions Dataset",
        engine="openpyxl",
    )

# Proposed feature mappings for Q001-Q040.
feature_mapping = {
    "Q001": ("interest_technology", "Rating 1-5", "Proposed"),
    "Q002": ("interest_data", "Rating 1-5", "Proposed"),
    "Q003": ("interest_technology", "Rating 1-5", "Proxy; review"),
    "Q004": ("interest_creativity", "Rating 1-5", "Proxy; review"),
    "Q005": ("interest_people", "Rating 1-5", "Proxy; review"),
    "Q006": ("interest_helping", "Rating 1-5", "Proxy; review"),
    "Q007": ("interest_people", "Rating 1-5", "Proxy; review"),
    "Q008": ("interest_data", "Rating 1-5", "Proxy; review"),
    "Q009": (None, "Rating 1-5", "Needs finance-interest feature"),
    "Q010": ("interest_problem_solving", "Rating 1-5", "Proxy; review"),

    "Q011": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q012": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q013": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q014": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q015": ("aptitude_critical_thinking", "Correct=1; incorrect=0", "Answer key supplied; review wording"),
    "Q016": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q017": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q018": ("aptitude_critical_thinking", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q019": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
    "Q020": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),

    "Q021": (None, "Agreement rating 1-5", "Needs teamwork/social feature"),
    "Q022": (None, "Agreement rating 1-5", "Needs trait and item-direction review"),
    "Q023": ("trait_extraversion", "Agreement rating 1-5", "Leadership proxy; review"),
    "Q024": ("trait_conscientiousness", "Agreement rating 1-5", "Proposed; review"),
    "Q025": ("trait_openness", "Agreement rating 1-5", "Proposed; review"),
    "Q026": ("trait_emotional_stability", "Agreement rating 1-5", "Proposed; review"),
    "Q027": (None, "Agreement rating 1-5", "Needs rule-adherence feature"),
    "Q028": ("trait_extraversion", "Agreement rating 1-5", "Proposed; review"),
    "Q029": (None, "Agreement rating 1-5", "Analytical thinking needs separate validation"),
    "Q030": (None, "Agreement rating 1-5", "Needs adaptability feature"),

    "Q031": ("skill_programming", "Rating 1-5; N/A=missing", "Proposed"),
    "Q032": ("skill_data_analysis", "Rating 1-5; N/A=missing", "Proposed"),
    "Q033": (None, "Rating 1-5; N/A=missing", "Needs design-skill feature"),
    "Q034": (None, "Rating 1-5; N/A=missing", "Needs finance-skill feature"),
    "Q035": (None, "Rating 1-5; N/A=missing", "Needs cybersecurity-skill feature"),
    "Q036": ("skill_leadership", "Rating 1-5; N/A=missing", "Project management proxy; review"),
    "Q037": (None, "Rating 1-5; N/A=missing", "Needs marketing-skill feature"),
    "Q038": (None, "Rating 1-5; N/A=missing", "Needs legal/policy-skill feature"),
    "Q039": (None, "Rating 1-5; N/A=missing", "Needs engineering-skill feature"),
    "Q040": ("skill_research", "Rating 1-5; N/A=missing", "Proposed"),
}

aptitude_answer_key = {
    "Q011": "B", "Q012": "D", "Q013": "C", "Q014": "A",
    "Q015": "C", "Q016": "B", "Q017": "B", "Q018": "A",
    "Q019": "C", "Q020": "C",
}

aptitude_dimensions = {
    qid: details[0]
    for qid, details in feature_mapping.items()
    if qid in aptitude_answer_key
}

mapping_40 = questions_df[
    questions_df["Question_ID"].isin(feature_mapping)
].copy()

mapping_40["Proposed_Feature"] = mapping_40["Question_ID"].map(
    lambda q: feature_mapping[q][0]
)
mapping_40["Proposed_Scoring_Method"] = mapping_40["Question_ID"].map(
    lambda q: feature_mapping[q][1]
)
mapping_40["Mapping_Status"] = mapping_40["Question_ID"].map(
    lambda q: feature_mapping[q][2]
)
mapping_40["Correct_Answer_Key"] = mapping_40["Question_ID"].map(
    aptitude_answer_key
)
mapping_40["Aptitude_Feature"] = mapping_40["Question_ID"].map(
    aptitude_dimensions
)

display(
    mapping_40[
        [
            "Question_ID",
            "Section",
            "Proposed_Feature",
            "Proposed_Scoring_Method",
            "Correct_Answer_Key",
            "Aptitude_Feature",
            "Mapping_Status",
        ]
    ].sort_values("Question_ID")
)

print("Questions mapped:", len(mapping_40))
print("Questions with proposed features:",
      mapping_40["Proposed_Feature"].notna().sum())
print("Questions needing a dedicated feature:",
      mapping_40["Proposed_Feature"].isna().sum())
print("Aptitude answer keys attached:",
      mapping_40["Correct_Answer_Key"].notna().sum())

,Question_ID,Section,Proposed_Feature,Proposed_Scoring_Method,Correct_Answer_Key,Aptitude_Feature,Mapping_Status
0,Q001,Interest,interest_technology,Rating 1-5,NaN,NaN,Proposed
1,Q002,Interest,interest_data,Rating 1-5,NaN,NaN,Proposed
2,Q003,Interest,interest_technology,Rating 1-5,NaN,NaN,Proxy; review
3,Q004,Interest,interest_creativity,Rating 1-5,NaN,NaN,Proxy; review
4,Q005,Interest,interest_people,Rating 1-5,NaN,NaN,Proxy; review
5,Q006,Interest,interest_helping,Rating 1-5,NaN,NaN,Proxy; review
6,Q007,Interest,interest_people,Rating 1-5,NaN,NaN,Proxy; review
7,Q008,Interest,interest_data,Rating 1-5,NaN,NaN,Proxy; review
8,Q009,Interest,NaN,Rating 1-5,NaN,NaN,Needs finance-interest feature
9,Q010,Interest,interest_problem_solving,Rating 1-5,NaN,NaN,Proxy; review
10,Q011,Aptitude,aptitude_numerical,Correct=1; incorrect=0,B,aptitude_numerical,Answer key supplied
11,Q012,Aptitude,aptitude_logical,Correct=1; incorrect=0,D,aptitude_logical,Answer key supplied
12,Q013,Aptitude,aptitude_numerical,Correct=1; incorrect=0,C,aptitude_numerical,Answer key supplied
13,Q014,Aptitude,aptitude_logical,Correct=1; incorrect=0,A,aptitude_logical,Answer key supplied
14,Q015,Aptitude,aptitude_critical_thinking,Correct=1; incorrect=0,C,aptitude_critical_thinking,Answer key supplied; review wording
15,Q016,Aptitude,aptitude_logical,Correct=1; incorrect=0,B,aptitude_logical,Answer key supplied
16,Q017,Aptitude,aptitude_numerical,Correct=1; incorrect=0,B,aptitude_numerical,Answer key supplied
17,Q018,Aptitude,aptitude_critical_thinking,Correct=1; incorrect=0,A,aptitude_critical_thinking,Answer key supplied
18,Q019,Aptitude,aptitude_logical,Correct=1; incorrect=0,C,aptitude_logical,Answer key supplied
19,Q020,Aptitude,aptitude_numerical,Correct=1; incorrect=0,C,aptitude_numerical,Answer key supplied
20,Q021,Personality,NaN,Agreement rating 1-5,NaN,NaN,Needs teamwork/social feature
21,Q022,Personality,NaN,Agreement rating 1-5,NaN,NaN,Needs trait and item-direction review
22,Q023,Personality,trait_extraversion,Agreement rating 1-5,NaN,NaN,Leadership proxy; review
23,Q024,Personality,trait_conscientiousness,Agreement rating 1-5,NaN,NaN,Proposed; review
24,Q025,Personality,trait_openness,Agreement rating 1-5,NaN,NaN,Proposed; review
25,Q026,Personality,trait_emotional_stability,Agreement rating 1-5,NaN,NaN,Proposed; review
26,Q027,Personality,NaN,Agreement rating 1-5,NaN,NaN,Needs rule-adherence feature
27,Q028,Personality,trait_extraversion,Agreement rating 1-5,NaN,NaN,Proposed; review
28,Q029,Personality,NaN,Agreement rating 1-5,NaN,NaN,Analytical thinking needs separate validation
29,Q030,Personality,NaN,Agreement rating 1-5,NaN,NaN,Needs adaptability feature
30,Q031,Skills,skill_programming,Rating 1-5; N/A=missing,NaN,NaN,Proposed
31,Q032,Skills,skill_data_analysis,Rating 1-5; N/A=missing,NaN,NaN,Proposed
32,Q033,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs design-skill feature
33,Q034,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs finance-skill feature
34,Q035,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs cybersecurity-skill feature
35,Q036,Skills,skill_leadership,Rating 1-5; N/A=missing,NaN,NaN,Project management proxy; review
36,Q037,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs marketing-skill feature
37,Q038,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs legal/policy-skill feature
38,Q039,Skills,NaN,Rating 1-5; N/A=missing,NaN,NaN,Needs engineering-skill feature
39,Q040,Skills,skill_research,Rating 1-5; N/A=missing,NaN,NaN,Proposed

Questions mapped: 40
Questions with proposed features: 28
Questions needing a dedicated feature: 12
Aptitude answer keys attached: 10

## Step 8B — Inspect career-preference questions Q041–Q120

In [13]:

# Step 8B: Inspect context and career-preference questions

career_preference_questions = questions_df[
    questions_df["Question_ID"].apply(
        lambda q: 41 <= int(str(q)[1:]) <= 120
    )
].copy()

print("Questions Q041-Q120:",
      len(career_preference_questions))

for section_name, group in career_preference_questions.groupby(
    "Section", sort=False
):
    print(f"\n--- {section_name} ---")
    display(
        group[
            [
                "Question_ID",
                "Question_Text",
                "Answer_Type",
                "Answer_Options",
                "Purpose",
            ]
        ].reset_index(drop=True)
    )

Questions Q041-Q120: 80

--- Education & Career Preferences ---

,Question_ID,Question_Text,Answer_Type,Answer_Options,Purpose
0,Q041,What is your current or most recently complete...,Dropdown,"High School, Diploma, Bachelor's, Master's, Ph...",General Education
1,Q042,Which broad academic field does your primary d...,Dropdown,"Engineering, Business, Arts, Sciences, Medicin...",General Education
2,Q043,What is your cumulative academic performance/G...,MCQ,"Top 10%, Top 25%, Average, Below Average, Pref...",General Education
3,Q044,Have you completed any specialized bootcamps o...,MCQ,"Yes - Technical, Yes - Non-Technical, No",General Education
4,Q045,How many total years of formal education/train...,MCQ,"<1 year, 1-3 years, 3-5 years, 5+ years",General Education
...,...,...,...,...,...
75,Q116,Do you prefer arguing cases in a courtroom or ...,MCQ,"Courtroom/Litigation, Corporate/Drafting, N/A",Domain Preference: Law & Public Service
76,Q117,How important is it for your work to directly ...,MCQ,"Very important, Somewhat, Not important",Domain Preference: Law & Public Service
77,Q118,Are you comfortable defending clients or polic...,MCQ,"Yes, No, Depends on the issue",Domain Preference: Law & Public Service
78,Q119,Do you prefer the fast pace of a corporate law...,MCQ,"Corporate Law Firm, Government/Public Sector, ...",Domain Preference: Law & Public Service
79,Q120,How comfortable are you reading and synthesizi...,MCQ,"Very comfortable, Somewhat, Uncomfortable",Domain Preference: Law & Public Service

## Step 8C — Inspect all 80 questions completely

In [14]:

# Step 8C: Display complete question text and options for Q041-Q120

import pandas as pd

# Ensure Question_ID values are handled consistently
questions_df["Question_ID"] = questions_df["Question_ID"].astype(str).str.strip()

career_questions = questions_df[
    questions_df["Question_ID"].str.match(r"^Q(0[4-9]\d|1[01]\d|120)$")
].copy()

# Display complete text without truncation
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

# Part 1: Education and general context (Q041-Q060)
general_questions = career_questions[
    career_questions["Question_ID"].str.extract(r"Q(\d+)")[0].astype(int).between(41, 60)
]

print("GENERAL EDUCATION AND CAREER CONTEXT — Q041 to Q060")
display(
    general_questions[
        ["Question_ID", "Question_Text", "Answer_Type", "Answer_Options", "Purpose"]
    ].reset_index(drop=True)
)

# Part 2: Career-domain preferences (Q061-Q120)
domain_questions = career_questions[
    career_questions["Question_ID"].str.extract(r"Q(\d+)")[0].astype(int).between(61, 120)
]

print("\nCAREER-DOMAIN PREFERENCES — Q061 to Q120")
display(
    domain_questions[
        ["Question_ID", "Question_Text", "Answer_Type", "Answer_Options", "Purpose"]
    ].reset_index(drop=True)
)

print("\nValidation")
print("General questions:", len(general_questions))
print("Domain preference questions:", len(domain_questions))
print("Total questions:", len(general_questions) + len(domain_questions))

GENERAL EDUCATION AND CAREER CONTEXT — Q041 to Q060

,Question_ID,Question_Text,Answer_Type,Answer_Options,Purpose
0,Q041,What is your current or most recently completed level of education?,Dropdown,"High School, Diploma, Bachelor's, Master's, PhD, Other",General Education
1,Q042,Which broad academic field does your primary degree or certification fall under?,Dropdown,"Engineering, Business, Arts, Sciences, Medicine, Law, None/Other",General Education
2,Q043,What is your cumulative academic performance/GPA equivalent?,MCQ,"Top 10%, Top 25%, Average, Below Average, Prefer not to say",General Education
3,Q044,Have you completed any specialized bootcamps or professional certifications outside of formal degrees?,MCQ,"Yes - Technical, Yes - Non-Technical, No",General Education
4,Q045,How many total years of formal education/training do you have in your primary field of interest?,MCQ,"<1 year, 1-3 years, 3-5 years, 5+ years",General Education
5,Q046,How many years of full-time professional work experience do you currently have?,MCQ,"0, <1, 1-3, 3-5, 5+",General Experience
6,Q047,"Have you ever completed an internship, apprenticeship, or practical training program?",MCQ,"Yes, No",General Experience
7,Q048,Have you ever held a leadership or management role where you were responsible for others?,MCQ,"Yes, No",General Experience
8,Q049,Do you have experience working as a freelancer or running your own business/startup?,MCQ,"Yes, No",General Experience
9,Q050,What is the largest team size you have consistently worked with?,MCQ,"Solo, 2-5, 6-15, 15+",General Experience
10,Q051,What is your primary career motivation?,MCQ,"High Salary, Work-Life Balance, Social Impact, Innovation/Building, Stability",Career Goals
11,Q052,What is your minimum acceptable starting salary expectation (in your local currency/tier)?,Dropdown,[List of standard ranges],Career Goals
12,Q053,Are you willing to relocate to a different city or country for the right career opportunity?,MCQ,"Yes, No, Only within my region",Career Goals
13,Q054,Where do you see yourself in 5 years?,MCQ,"Individual Contributor/Expert, Manager/Leader, Entrepreneur, Academic/Researcher",Career Goals
14,Q055,"How important is job security and stability compared to rapid, high-risk career growth?",MCQ,"Highly prefer stability, Balance of both, Highly prefer rapid growth",Career Goals
15,Q056,What is your preferred working environment?,MCQ,"100% Remote, Hybrid, 100% On-site",Preferred Environment
16,Q057,Which company size do you prefer working for?,MCQ,"Early-stage Startup, Mid-size Enterprise, Large Multinational Corporate, Government/Public Sector",Preferred Environment
17,Q058,Are you willing to travel frequently (more than 30% of the time) for work?,MCQ,"Yes, No, Occasionally",Preferred Environment
18,Q059,Do you prefer a predictable 9-to-5 schedule or flexible hours that may require occasional nights/weekends?,MCQ,"Strict 9-5, Flexible/Results-oriented",Preferred Environment
19,Q060,How do you prefer to be evaluated at work?,MCQ,"By measurable data/KPIs, By project completion/portfolio, By peer/manager reviews",Preferred Environment

CAREER-DOMAIN PREFERENCES — Q061 to Q120

,Question_ID,Question_Text,Answer_Type,Answer_Options,Purpose
0,Q061,Which aspect of software development interests you the most?,MCQ,"Frontend/UI, Backend/Server, Mobile Apps, Architecture",Domain Preference: Software Development
1,Q062,Are you willing to participate in on-call rotations for emergency system outages?,MCQ,"Yes, No, Unsure",Domain Preference: Software Development
2,Q063,Do you prefer building consumer-facing applications or internal enterprise tools?,MCQ,"Consumer-facing, Internal tools, No preference",Domain Preference: Software Development
3,Q064,How comfortable are you with continuous integration and rapid deployment cycles?,MCQ,"Very comfortable, Somewhat, Prefer slower releases, Not applicable",Domain Preference: Software Development
4,Q065,Which software ecosystem do you prefer working in?,MCQ,"Open Source/Linux, Microsoft/Enterprise, Apple/iOS, Agnostic",Domain Preference: Software Development
5,Q066,Do you prefer building predictive machine learning models or creating dashboards/reports for business leaders?,MCQ,"ML Models, Dashboards, Both equally",Domain Preference: Data Science
6,Q067,"Are you comfortable dealing with messy, unstructured data that requires heavy cleaning?",MCQ,"Yes, No, Unsure",Domain Preference: Data Science
7,Q068,Do you prefer deep-diving into a single complex algorithm or applying multiple standard algorithms rapidly?,MCQ,"Deep dive, Rapid application",Domain Preference: Data Science
8,Q069,"How important is it for you to work with cutting-edge AI technologies (e.g., LLMs, Computer Vision)?",MCQ,"Mandatory, Nice to have, Not important",Domain Preference: Data Science
9,Q070,Are you comfortable presenting complex statistical findings to non-technical stakeholders?,MCQ,"Yes, No, Unsure",Domain Preference: Data Science
10,Q071,Do you prefer offensive security (Red Team/Penetration Testing) or defensive security (Blue Team/Incident Response)?,MCQ,"Offensive, Defensive, Both/Purple",Domain Preference: Cybersecurity
11,Q072,Are you willing to undergo extensive background checks and maintain government security clearances?,MCQ,"Yes, No",Domain Preference: Cybersecurity
12,Q073,"How comfortable are you working in high-stress, time-critical incident response scenarios?",MCQ,"Very comfortable, Somewhat, Prefer low-stress",Domain Preference: Cybersecurity
13,Q074,"Do you prefer auditing policies and compliance, or actively hunting for technical vulnerabilities?",MCQ,"Compliance/Policy, Technical Hunting",Domain Preference: Cybersecurity
14,Q075,Are you willing to continually study new threat vectors outside of standard work hours?,MCQ,"Yes, No",Domain Preference: Cybersecurity
15,Q076,"Do you prefer conducting user research (interviews, surveys) or creating high-fidelity visual designs?",MCQ,"User Research, Visual Design, Both equally",Domain Preference: UI/UX Design
16,Q077,How comfortable are you adapting your designs based on strict technical limitations from developers?,MCQ,"Very comfortable, Somewhat, Frustrating",Domain Preference: UI/UX Design
17,Q078,Do you prefer working on entirely new product concepts or optimizing existing legacy interfaces?,MCQ,"New concepts, Optimizing existing",Domain Preference: UI/UX Design
18,Q079,How important is establishing and maintaining a strict design system (component library) to you?,MCQ,"Very important, Somewhat, Prefer ad-hoc design",Domain Preference: UI/UX Design
19,Q080,Are you comfortable defending your design choices to stakeholders using qualitative data?,MCQ,"Yes, No",Domain Preference: UI/UX Design
20,Q081,"Do you prefer managing people (HR, team dynamics) or managing processes (Agile, supply chain)?",MCQ,"People, Processes, Both",Domain Preference: Business & Management
21,Q082,How comfortable are you taking responsibility for a project's financial profit and loss (P&L)?,MCQ,"Very comfortable, Somewhat, Prefer to avoid",Domain Preference: Business & Management
22,Q083,Do you prefer strategizing long-term corporate visions or executing short-term operational goals?,MCQ,"Long-term strategy, Short-term execution",Domain Preference: Business & Management
23,Q084,Are you comfortable resolving interpersonal conflicts between team members on a regular basis?,MCQ,"Yes, No",Domain Preference: Business & Management
24,Q085,"How important is having a clear, hierarchical path to executive leadership to you?",MCQ,"Very important, Nice to have, Not important",Domain Preference: Business & Management
25,Q086,Do you prefer interacting directly with patients or working behind the scenes in a laboratory/research setting?,MCQ,"Direct patient care, Laboratory/Research",Domain Preference: Healthcare
26,Q087,"How comfortable are you dealing with bodily fluids, severe illnesses, or emergency medical trauma?",MCQ,"Comfortable, Uncomfortable, Unsure",Domain Preference: Healthcare
27,Q088,"Are you willing to work irregular shifts, including nights, weekends, and holidays?",MCQ,"Yes, No, Only if necessary",Domain Preference: Healthcare
28,Q089,Do you prefer clinical practice or biomedical research?,MCQ,"Clinical, Research",Domain Preference: Healthcare
29,Q090,How comfortable are you navigating strict healthcare regulations and medical documentation procedures?,MCQ,"Very comfortable, Somewhat, Prefer to avoid",Domain Preference: Healthcare
30,Q091,What age group do you most prefer teaching or designing educational content for?,MCQ,"Early Childhood, K-12, Higher Ed/University, Adult/Corporate",Domain Preference: Education & Research
31,Q092,Do you prefer lecturing in front of large groups or providing 1-on-1 mentorship?,MCQ,"Large groups, 1-on-1, Both equally",Domain Preference: Education & Research
32,Q093,How important is tenure or long-term academic job security to your career plan?,MCQ,"Very important, Somewhat, Not important",Domain Preference: Education & Research
33,Q094,Do you prefer focusing on pedagogy (how to teach) or deep subject-matter expertise (what to teach)?,MCQ,"Pedagogy, Subject Matter",Domain Preference: Education & Research
34,Q095,"Are you comfortable dedicating significant time to grading, curriculum planning, and administrative duties?",MCQ,"Yes, No",Domain Preference: Education & Research
35,Q096,Do you prefer data-driven marketing or creative marketing?,MCQ,"Data-driven, Creative, Both",Domain Preference: Digital Marketing
36,Q097,How comfortable are you pivoting campaigns rapidly based on daily social media trends?,MCQ,"Very comfortable, Prefer long-term planned campaigns",Domain Preference: Digital Marketing
37,Q098,Do you prefer B2B or B2C marketing environments?,MCQ,"B2B, B2C, No preference",Domain Preference: Digital Marketing
38,Q099,Are you comfortable managing large advertising budgets where ROI must be strictly justified?,MCQ,"Yes, No",Domain Preference: Digital Marketing
39,Q100,"How important is public visibility (e.g., managing influencer relations, PR) in your ideal role?",MCQ,"Very important, Somewhat, Prefer behind the scenes",Domain Preference: Digital Marketing
40,Q101,Do you prefer corporate accounting or investment finance?,MCQ,"Accounting, Investment Finance",Domain Preference: Finance & Accounting
41,Q102,How comfortable are you making high-stakes financial decisions based on incomplete market data?,MCQ,"Very comfortable, Prefer having all data, Uncomfortable",Domain Preference: Finance & Accounting
42,Q103,Are you willing to work extremely long hours during tax season or deal closures?,MCQ,"Yes, No, Only occasionally",Domain Preference: Finance & Accounting
43,Q104,Do you prefer client-facing advisory roles or quantitative analysis?,MCQ,"Advisory, Quantitative Analysis",Domain Preference: Finance & Accounting
44,Q105,"How important is obtaining prestigious certifications (e.g., CPA, CFA) to your career trajectory?",MCQ,"Mandatory, Nice to have, Not necessary",Domain Preference: Finance & Accounting
45,Q106,Which branch of core engineering aligns closest to your interests?,MCQ,"Mechanical/Automotive, Civil/Structural, Electrical/Electronics, Chemical/Materials",Domain Preference: Engineering & Tech
46,Q107,Do you prefer hands-on fieldwork/manufacturing floors or office-based CAD design and simulation?,MCQ,"Fieldwork/Hands-on, Office/CAD, Mix of both",Domain Preference: Engineering & Tech
47,Q108,How comfortable are you adhering to strict safety protocols and municipal codes?,MCQ,"Very comfortable, Somewhat, Find them restrictive",Domain Preference: Engineering & Tech
48,Q109,Are you willing to be deployed to remote industrial sites for weeks at a time?,MCQ,"Yes, No",Domain Preference: Engineering & Tech
49,Q110,Do you prefer maintaining and optimizing existing infrastructure or designing entirely new systems?,MCQ,"Maintaining/Optimizing, Designing new",Domain Preference: Engineering & Tech
50,Q111,Do you prefer commercial art or fine art?,MCQ,"Commercial, Fine Art",Domain Preference: Creative Arts & Media
51,Q112,Which medium do you prefer working with?,MCQ,"Digital/Graphic, Video/Film, Audio/Music, Physical/Sculpture/Paint",Domain Preference: Creative Arts & Media
52,Q113,"How comfortable are you with fluctuating, gig-based income rather than a steady corporate salary?",MCQ,"Very comfortable, Somewhat, Prefer steady salary",Domain Preference: Creative Arts & Media
53,Q114,Are you able to separate your personal ego from your work when a client demands heavy revisions?,MCQ,"Yes easily, Sometimes difficult, No",Domain Preference: Creative Arts & Media
54,Q115,Do you prefer working solo in a studio or on a bustling set with a large production crew?,MCQ,"Solo, Large crew",Domain Preference: Creative Arts & Media
55,Q116,Do you prefer arguing cases in a courtroom or drafting contracts and advising behind the scenes?,MCQ,"Courtroom/Litigation, Corporate/Drafting, N/A",Domain Preference: Law & Public Service
56,Q117,How important is it for your work to directly influence public policy or government administration?,MCQ,"Very important, Somewhat, Not important",Domain Preference: Law & Public Service
57,Q118,Are you comfortable defending clients or policies that you personally disagree with?,MCQ,"Yes, No, Depends on the issue",Domain Preference: Law & Public Service
58,Q119,Do you prefer the fast pace of a corporate law firm or the stability of government/public sector work?,MCQ,"Corporate Law Firm, Government/Public Sector, NGO/Non-profit",Domain Preference: Law & Public Service
59,Q120,How comfortable are you reading and synthesizing hundreds of pages of dense legal precedent daily?,MCQ,"Very comfortable, Somewhat, Uncomfortable",Domain Preference: Law & Public Service

Validation
General questions: 20
Domain preference questions: 60
Total questions: 80

## Step 8D — Create the Q041–Q120 mapping table

In [15]:

# Step 8D: Map Q041-Q120 to profile and career-preference features

import pandas as pd
import re

# Ensure question IDs are consistent
questions_df["Question_ID"] = questions_df["Question_ID"].astype(str).str.strip()

# Feature names for Q041-Q060: profile and context
profile_features = {
    "Q041": "profile_education_level",
    "Q042": "profile_academic_field",
    "Q043": "profile_academic_performance",
    "Q044": "profile_certification_status",
    "Q045": "profile_training_duration",
    "Q046": "profile_work_experience",
    "Q047": "profile_internship_experience",
    "Q048": "profile_leadership_experience",
    "Q049": "profile_freelance_business_experience",
    "Q050": "profile_team_size_experience",
    "Q051": "profile_primary_career_motivation",
    "Q052": "profile_minimum_salary_expectation",
    "Q053": "profile_relocation_willingness",
    "Q054": "profile_five_year_goal",
    "Q055": "profile_stability_growth_preference",
    "Q056": "profile_work_environment",
    "Q057": "profile_company_size_preference",
    "Q058": "profile_travel_willingness",
    "Q059": "profile_work_schedule_preference",
    "Q060": "profile_performance_evaluation_preference",
}

# Map domain names from the questionnaire's Purpose column
domain_slug_map = {
    "Software Development": "software_development",
    "Data Science": "data_science",
    "Cybersecurity": "cybersecurity",
    "UI/UX Design": "ui_ux_design",
    "Business & Management": "business_management",
    "Healthcare": "healthcare",
    "Education & Research": "education_research",
    "Digital Marketing": "digital_marketing",
    "Finance & Accounting": "finance_accounting",
    "Engineering & Tech": "engineering_technology",
    "Creative Arts & Media": "creative_arts_media",
    "Law & Public Service": "law_public_service",
}

mapping_records = []

for _, row in questions_df.iterrows():
    qid = row["Question_ID"]
    match = re.fullmatch(r"Q(\d{3})", qid)

    if not match:
        continue

    q_num = int(match.group(1))

    if 41 <= q_num <= 60:
        feature = profile_features[qid]
        scoring = (
            "Preserve selected category; encode categorically. "
            "Use ordinal encoding only when option order is meaningful."
        )
        status = "Proposed profile feature; validate encoding"

    elif 61 <= q_num <= 120:
        purpose = str(row.get("Purpose", "")).strip()
        domain = purpose.replace("Domain Preference:", "").strip()
        slug = domain_slug_map.get(domain)

        if slug is None:
            feature = None
            scoring = "Review Purpose and define domain mapping"
            status = "Needs review"
        else:
            feature = f"career_pref_{slug}_{qid.lower()}"
            scoring = (
                "Preserve selected option; one-hot encode nominal options "
                "or use justified ordinal encoding. Define domain weights later."
            )
            status = "Proposed domain-preference feature; validate scoring"

    else:
        continue

    mapping_records.append({
        "Question_ID": qid,
        "Section": row.get("Section"),
        "Question_Text": row.get("Question_Text"),
        "Answer_Type": row.get("Answer_Type"),
        "Answer_Options": row.get("Answer_Options"),
        "Purpose": row.get("Purpose"),
        "Proposed_Feature": feature,
        "Proposed_Scoring_Method": scoring,
        "Mapping_Status": status,
    })

mapping_80 = pd.DataFrame(mapping_records)

# Sort numerically by question ID
mapping_80["_number"] = mapping_80["Question_ID"].str[1:].astype(int)
mapping_80 = mapping_80.sort_values("_number").drop(columns="_number")

display(mapping_80)

print("Questions mapped:", len(mapping_80))
print("Missing proposed features:", mapping_80["Proposed_Feature"].isna().sum())
print("Profile questions:", mapping_80["Question_ID"].str[1:].astype(int).between(41, 60).sum())
print("Domain-preference questions:", mapping_80["Question_ID"].str[1:].astype(int).between(61, 120).sum())

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Purpose,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
0,Q041,Education & Career Preferences,What is your current or most recently completed level of education?,Dropdown,"High School, Diploma, Bachelor's, Master's, PhD, Other",General Education,profile_education_level,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
1,Q042,Education & Career Preferences,Which broad academic field does your primary degree or certification fall under?,Dropdown,"Engineering, Business, Arts, Sciences, Medicine, Law, None/Other",General Education,profile_academic_field,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
2,Q043,Education & Career Preferences,What is your cumulative academic performance/GPA equivalent?,MCQ,"Top 10%, Top 25%, Average, Below Average, Prefer not to say",General Education,profile_academic_performance,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
3,Q044,Education & Career Preferences,Have you completed any specialized bootcamps or professional certifications outside of formal degrees?,MCQ,"Yes - Technical, Yes - Non-Technical, No",General Education,profile_certification_status,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
4,Q045,Education & Career Preferences,How many total years of formal education/training do you have in your primary field of interest?,MCQ,"<1 year, 1-3 years, 3-5 years, 5+ years",General Education,profile_training_duration,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
5,Q046,Education & Career Preferences,How many years of full-time professional work experience do you currently have?,MCQ,"0, <1, 1-3, 3-5, 5+",General Experience,profile_work_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
6,Q047,Education & Career Preferences,"Have you ever completed an internship, apprenticeship, or practical training program?",MCQ,"Yes, No",General Experience,profile_internship_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
7,Q048,Education & Career Preferences,Have you ever held a leadership or management role where you were responsible for others?,MCQ,"Yes, No",General Experience,profile_leadership_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
8,Q049,Education & Career Preferences,Do you have experience working as a freelancer or running your own business/startup?,MCQ,"Yes, No",General Experience,profile_freelance_business_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
9,Q050,Education & Career Preferences,What is the largest team size you have consistently worked with?,MCQ,"Solo, 2-5, 6-15, 15+",General Experience,profile_team_size_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
10,Q051,Education & Career Preferences,What is your primary career motivation?,MCQ,"High Salary, Work-Life Balance, Social Impact, Innovation/Building, Stability",Career Goals,profile_primary_career_motivation,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
11,Q052,Education & Career Preferences,What is your minimum acceptable starting salary expectation (in your local currency/tier)?,Dropdown,[List of standard ranges],Career Goals,profile_minimum_salary_expectation,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
12,Q053,Education & Career Preferences,Are you willing to relocate to a different city or country for the right career opportunity?,MCQ,"Yes, No, Only within my region",Career Goals,profile_relocation_willingness,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
13,Q054,Education & Career Preferences,Where do you see yourself in 5 years?,MCQ,"Individual Contributor/Expert, Manager/Leader, Entrepreneur, Academic/Researcher",Career Goals,profile_five_year_goal,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
14,Q055,Education & Career Preferences,"How important is job security and stability compared to rapid, high-risk career growth?",MCQ,"Highly prefer stability, Balance of both, Highly prefer rapid growth",Career Goals,profile_stability_growth_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
15,Q056,Education & Career Preferences,What is your preferred working environment?,MCQ,"100% Remote, Hybrid, 100% On-site",Preferred Environment,profile_work_environment,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
16,Q057,Education & Career Preferences,Which company size do you prefer working for?,MCQ,"Early-stage Startup, Mid-size Enterprise, Large Multinational Corporate, Government/Public Sector",Preferred Environment,profile_company_size_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
17,Q058,Education & Career Preferences,Are you willing to travel frequently (more than 30% of the time) for work?,MCQ,"Yes, No, Occasionally",Preferred Environment,profile_travel_willingness,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
18,Q059,Education & Career Preferences,Do you prefer a predictable 9-to-5 schedule or flexible hours that may require occasional nights/weekends?,MCQ,"Strict 9-5, Flexible/Results-oriented",Preferred Environment,profile_work_schedule_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
19,Q060,Education & Career Preferences,How do you prefer to be evaluated at work?,MCQ,"By measurable data/KPIs, By project completion/portfolio, By peer/manager reviews",Preferred Environment,profile_performance_evaluation_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
20,Q061,Education & Career Preferences,Which aspect of software development interests you the most?,MCQ,"Frontend/UI, Backend/Server, Mobile Apps, Architecture",Domain Preference: Software Development,career_pref_software_development_q061,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
21,Q062,Education & Career Preferences,Are you willing to participate in on-call rotations for emergency system outages?,MCQ,"Yes, No, Unsure",Domain Preference: Software Development,career_pref_software_development_q062,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
22,Q063,Education & Career Preferences,Do you prefer building consumer-facing applications or internal enterprise tools?,MCQ,"Consumer-facing, Internal tools, No preference",Domain Preference: Software Development,career_pref_software_development_q063,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
23,Q064,Education & Career Preferences,How comfortable are you with continuous integration and rapid deployment cycles?,MCQ,"Very comfortable, Somewhat, Prefer slower releases, Not applicable",Domain Preference: Software Development,career_pref_software_development_q064,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
24,Q065,Education & Career Preferences,Which software ecosystem do you prefer working in?,MCQ,"Open Source/Linux, Microsoft/Enterprise, Apple/iOS, Agnostic",Domain Preference: Software Development,career_pref_software_development_q065,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
25,Q066,Education & Career Preferences,Do you prefer building predictive machine learning models or creating dashboards/reports for business leaders?,MCQ,"ML Models, Dashboards, Both equally",Domain Preference: Data Science,career_pref_data_science_q066,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
26,Q067,Education & Career Preferences,"Are you comfortable dealing with messy, unstructured data that requires heavy cleaning?",MCQ,"Yes, No, Unsure",Domain Preference: Data Science,career_pref_data_science_q067,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
27,Q068,Education & Career Preferences,Do you prefer deep-diving into a single complex algorithm or applying multiple standard algorithms rapidly?,MCQ,"Deep dive, Rapid application",Domain Preference: Data Science,career_pref_data_science_q068,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
28,Q069,Education & Career Preferences,"How important is it for you to work with cutting-edge AI technologies (e.g., LLMs, Computer Vision)?",MCQ,"Mandatory, Nice to have, Not important",Domain Preference: Data Science,career_pref_data_science_q069,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
29,Q070,Education & Career Preferences,Are you comfortable presenting complex statistical findings to non-technical stakeholders?,MCQ,"Yes, No, Unsure",Domain Preference: Data Science,career_pref_data_science_q070,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
30,Q071,Education & Career Preferences,Do you prefer offensive security (Red Team/Penetration Testing) or defensive security (Blue Team/Incident Response)?,MCQ,"Offensive, Defensive, Both/Purple",Domain Preference: Cybersecurity,career_pref_cybersecurity_q071,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
31,Q072,Education & Career Preferences,Are you willing to undergo extensive background checks and maintain government security clearances?,MCQ,"Yes, No",Domain Preference: Cybersecurity,career_pref_cybersecurity_q072,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
32,Q073,Education & Career Preferences,"How comfortable are you working in high-stress, time-critical incident response scenarios?",MCQ,"Very comfortable, Somewhat, Prefer low-stress",Domain Preference: Cybersecurity,career_pref_cybersecurity_q073,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
33,Q074,Education & Career Preferences,"Do you prefer auditing policies and compliance, or actively hunting for technical vulnerabilities?",MCQ,"Compliance/Policy, Technical Hunting",Domain Preference: Cybersecurity,career_pref_cybersecurity_q074,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
34,Q075,Education & Career Preferences,Are you willing to continually study new threat vectors outside of standard work hours?,MCQ,"Yes, No",Domain Preference: Cybersecurity,career_pref_cybersecurity_q075,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
35,Q076,Education & Career Preferences,"Do you prefer conducting user research (interviews, surveys) or creating high-fidelity visual designs?",MCQ,"User Research, Visual Design, Both equally",Domain Preference: UI/UX Design,career_pref_ui_ux_design_q076,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
36,Q077,Education & Career Preferences,How comfortable are you adapting your designs based on strict technical limitations from developers?,MCQ,"Very comfortable, Somewhat, Frustrating",Domain Preference: UI/UX Design,career_pref_ui_ux_design_q077,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
37,Q078,Education & Career Preferences,Do you prefer working on entirely new product concepts or optimizing existing legacy interfaces?,MCQ,"New concepts, Optimizing existing",Domain Preference: UI/UX Design,career_pref_ui_ux_design_q078,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
38,Q079,Education & Career Preferences,How important is establishing and maintaining a strict design system (component library) to you?,MCQ,"Very important, Somewhat, Prefer ad-hoc design",Domain Preference: UI/UX Design,career_pref_ui_ux_design_q079,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
39,Q080,Education & Career Preferences,Are you comfortable defending your design choices to stakeholders using qualitative data?,MCQ,"Yes, No",Domain Preference: UI/UX Design,career_pref_ui_ux_design_q080,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
40,Q081,Education & Career Preferences,"Do you prefer managing people (HR, team dynamics) or managing processes (Agile, supply chain)?",MCQ,"People, Processes, Both",Domain Preference: Business & Management,career_pref_business_management_q081,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
41,Q082,Education & Career Preferences,How comfortable are you taking responsibility for a project's financial profit and loss (P&L)?,MCQ,"Very comfortable, Somewhat, Prefer to avoid",Domain Preference: Business & Management,career_pref_business_management_q082,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
42,Q083,Education & Career Preferences,Do you prefer strategizing long-term corporate visions or executing short-term operational goals?,MCQ,"Long-term strategy, Short-term execution",Domain Preference: Business & Management,career_pref_business_management_q083,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
43,Q084,Education & Career Preferences,Are you comfortable resolving interpersonal conflicts between team members on a regular basis?,MCQ,"Yes, No",Domain Preference: Business & Management,career_pref_business_management_q084,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
44,Q085,Education & Career Preferences,"How important is having a clear, hierarchical path to executive leadership to you?",MCQ,"Very important, Nice to have, Not important",Domain Preference: Business & Management,career_pref_business_management_q085,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
45,Q086,Education & Career Preferences,Do you prefer interacting directly with patients or working behind the scenes in a laboratory/research setting?,MCQ,"Direct patient care, Laboratory/Research",Domain Preference: Healthcare,career_pref_healthcare_q086,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
46,Q087,Education & Career Preferences,"How comfortable are you dealing with bodily fluids, severe illnesses, or emergency medical trauma?",MCQ,"Comfortable, Uncomfortable, Unsure",Domain Preference: Healthcare,career_pref_healthcare_q087,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
47,Q088,Education & Career Preferences,"Are you willing to work irregular shifts, including nights, weekends, and holidays?",MCQ,"Yes, No, Only if necessary",Domain Preference: Healthcare,career_pref_healthcare_q088,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
48,Q089,Education & Career Preferences,Do you prefer clinical practice or biomedical research?,MCQ,"Clinical, Research",Domain Preference: Healthcare,career_pref_healthcare_q089,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
49,Q090,Education & Career Preferences,How comfortable are you navigating strict healthcare regulations and medical documentation procedures?,MCQ,"Very comfortable, Somewhat, Prefer to avoid",Domain Preference: Healthcare,career_pref_healthcare_q090,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring

Questions mapped: 80
Missing proposed features: 0
Profile questions: 20
Domain-preference questions: 60

## Step 8E — Save the mapping

In [16]:

# Save the proposed Q041-Q120 mapping
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

output_path = PROJECT_DIR / "Question_Mapping_Q041_Q120.csv"
mapping_80.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Mapping saved to:", output_path)

Mapping saved to: C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset\Question_Mapping_Q041_Q120.csv

## Step 8F — Combine all 120 questions

In [17]:

# Step 8F: Create the complete 120-question mapping table

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

# Load questions if they are not already in memory
if "questions_df" not in globals():
    questions_df = pd.read_excel(
        PROJECT_DIR / "AI_Career_Guidance_Questions.xlsx",
        sheet_name="Questions Dataset",
        engine="openpyxl",
    )

questions_df["Question_ID"] = questions_df["Question_ID"].astype(str).str.strip()

# Load the Q041-Q120 mapping saved in Step 8E
mapping_80_path = PROJECT_DIR / "Question_Mapping_Q041_Q120.csv"

if not mapping_80_path.exists():
    raise FileNotFoundError(
        f"Mapping file not found: {mapping_80_path}\n"
        "Run Step 8D and Step 8E first."
    )

mapping_80 = pd.read_csv(mapping_80_path)

# Reconstruct the Q001-Q040 mapping if mapping_40 is not in memory
if "mapping_40" not in globals():
    feature_mapping = {
        "Q001": ("interest_technology", "Rating 1-5", "Proposed"),
        "Q002": ("interest_data", "Rating 1-5", "Proposed"),
        "Q003": ("interest_technology", "Rating 1-5", "Proxy; review"),
        "Q004": ("interest_creativity", "Rating 1-5", "Proxy; review"),
        "Q005": ("interest_people", "Rating 1-5", "Proxy; review"),
        "Q006": ("interest_helping", "Rating 1-5", "Proxy; review"),
        "Q007": ("interest_people", "Rating 1-5", "Proxy; review"),
        "Q008": ("interest_data", "Rating 1-5", "Proxy; review"),
        "Q009": (None, "Rating 1-5", "Needs finance-interest feature"),
        "Q010": ("interest_problem_solving", "Rating 1-5", "Proxy; review"),
        "Q011": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q012": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q013": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q014": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q015": ("aptitude_critical_thinking", "Correct=1; incorrect=0", "Answer key supplied; review wording"),
        "Q016": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q017": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q018": ("aptitude_critical_thinking", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q019": ("aptitude_logical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q020": ("aptitude_numerical", "Correct=1; incorrect=0", "Answer key supplied"),
        "Q021": (None, "Agreement rating 1-5", "Needs teamwork/social feature"),
        "Q022": (None, "Agreement rating 1-5", "Needs trait and item-direction review"),
        "Q023": ("trait_extraversion", "Agreement rating 1-5", "Leadership proxy; review"),
        "Q024": ("trait_conscientiousness", "Agreement rating 1-5", "Proposed; review"),
        "Q025": ("trait_openness", "Agreement rating 1-5", "Proposed; review"),
        "Q026": ("trait_emotional_stability", "Agreement rating 1-5", "Proposed; review"),
        "Q027": (None, "Agreement rating 1-5", "Needs rule-adherence feature"),
        "Q028": ("trait_extraversion", "Agreement rating 1-5", "Proposed; review"),
        "Q029": (None, "Agreement rating 1-5", "Analytical thinking needs separate validation"),
        "Q030": (None, "Agreement rating 1-5", "Needs adaptability feature"),
        "Q031": ("skill_programming", "Rating 1-5; N/A=missing", "Proposed"),
        "Q032": ("skill_data_analysis", "Rating 1-5; N/A=missing", "Proposed"),
        "Q033": (None, "Rating 1-5; N/A=missing", "Needs design-skill feature"),
        "Q034": (None, "Rating 1-5; N/A=missing", "Needs finance-skill feature"),
        "Q035": (None, "Rating 1-5; N/A=missing", "Needs cybersecurity-skill feature"),
        "Q036": ("skill_leadership", "Rating 1-5; N/A=missing", "Project management proxy; review"),
        "Q037": (None, "Rating 1-5; N/A=missing", "Needs marketing-skill feature"),
        "Q038": (None, "Rating 1-5; N/A=missing", "Needs legal/policy-skill feature"),
        "Q039": (None, "Rating 1-5; N/A=missing", "Needs engineering-skill feature"),
        "Q040": ("skill_research", "Rating 1-5; N/A=missing", "Proposed"),
    }

    aptitude_answer_key = {
        "Q011": "B", "Q012": "D", "Q013": "C", "Q014": "A",
        "Q015": "C", "Q016": "B", "Q017": "B", "Q018": "A",
        "Q019": "C", "Q020": "C",
    }

    aptitude_dimensions = {
        qid: details[0]
        for qid, details in feature_mapping.items()
        if qid in aptitude_answer_key
    }

    mapping_40 = questions_df[
        questions_df["Question_ID"].isin(feature_mapping)
    ].copy()

    mapping_40["Proposed_Feature"] = mapping_40["Question_ID"].map(
        lambda q: feature_mapping[q][0]
    )
    mapping_40["Proposed_Scoring_Method"] = mapping_40["Question_ID"].map(
        lambda q: feature_mapping[q][1]
    )
    mapping_40["Mapping_Status"] = mapping_40["Question_ID"].map(
        lambda q: feature_mapping[q][2]
    )
    mapping_40["Correct_Answer_Key"] = mapping_40["Question_ID"].map(
        aptitude_answer_key
    )
    mapping_40["Aptitude_Feature"] = mapping_40["Question_ID"].map(
        aptitude_dimensions
    )

# Keep the common mapping columns
common_columns = [
    "Question_ID", "Section", "Question_Text", "Answer_Type",
    "Answer_Options", "Purpose", "Proposed_Feature",
    "Proposed_Scoring_Method", "Mapping_Status"
]

# Add missing source columns to the first 40 mapping if needed
for col in common_columns:
    if col not in mapping_40.columns:
        mapping_40[col] = pd.NA

for col in common_columns:
    if col not in mapping_80.columns:
        mapping_80[col] = pd.NA

mapping_120 = pd.concat(
    [mapping_40[common_columns], mapping_80[common_columns]],
    ignore_index=True,
)

mapping_120["_number"] = mapping_120["Question_ID"].str.extract(
    r"Q(\d+)"
).astype(int)

mapping_120 = mapping_120.sort_values("_number").drop(columns="_number")
mapping_120 = mapping_120.drop_duplicates(subset="Question_ID", keep="first")

# Save the complete mapping
output_path = PROJECT_DIR / "Question_Mapping_All_120.csv"
mapping_120.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Total mapped questions:", len(mapping_120))
print("Unique question IDs:", mapping_120["Question_ID"].nunique())
print("Missing feature mappings:", mapping_120["Proposed_Feature"].isna().sum())
print("Saved to:", output_path)

display(mapping_120.head(10))
display(mapping_120.tail(10))

Total mapped questions: 120
Unique question IDs: 120
Missing feature mappings: 12
Saved to: C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset\Question_Mapping_All_120.csv

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Purpose,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
0,Q001,Interest,"How interested are you in writing scripts or code to automate complex, repetitive tasks?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in core programming and logic,interest_technology,Rating 1-5,Proposed
1,Q002,Interest,How interested are you in analyzing large datasets to identify hidden trends and predict future outcomes?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in data science and statistical analysis,interest_data,Rating 1-5,Proposed
2,Q003,Interest,How interested are you in finding vulnerabilities in computer networks and systems to prevent unauthorized access?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in cybersecurity and risk mitigation,interest_technology,Rating 1-5,Proxy; review
3,Q004,Interest,How interested are you in sketching out wireframes and designing the visual layout of a mobile application?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in UI/UX and user-centric design,interest_creativity,Rating 1-5,Proxy; review
4,Q005,Interest,"How interested are you in coordinating team members, managing budgets, and overseeing a project from start to finish?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in business management and leadership,interest_people,Rating 1-5,Proxy; review
5,Q006,Interest,"How interested are you in studying human anatomy, diseases, or working directly to improve patient health?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in healthcare and life sciences,interest_helping,Rating 1-5,Proxy; review
6,Q007,Interest,How interested are you in explaining difficult concepts to others or developing instructional materials?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,"Measures interest in education, teaching, and academia",interest_people,Rating 1-5,Proxy; review
7,Q008,Interest,How interested are you in analyzing search engine algorithms and creating campaigns to increase website traffic?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in digital marketing and growth strategy,interest_data,Rating 1-5,Proxy; review
8,Q009,Interest,"How interested are you in auditing financial records, calculating risk, and forecasting company revenue?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,"Measures interest in finance, accounting, and quantitative economics",NaN,Rating 1-5,Needs finance-interest feature
9,Q010,Interest,"How interested are you in designing physical machines, circuits, or infrastructure using physics and mathematics?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,"Measures interest in core engineering (mechanical, civil, electrical)",interest_problem_solving,Rating 1-5,Proxy; review

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Purpose,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
110,Q111,Education & Career Preferences,Do you prefer commercial art or fine art?,MCQ,"Commercial, Fine Art",Domain Preference: Creative Arts & Media,career_pref_creative_arts_media_q111,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
111,Q112,Education & Career Preferences,Which medium do you prefer working with?,MCQ,"Digital/Graphic, Video/Film, Audio/Music, Physical/Sculpture/Paint",Domain Preference: Creative Arts & Media,career_pref_creative_arts_media_q112,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
112,Q113,Education & Career Preferences,"How comfortable are you with fluctuating, gig-based income rather than a steady corporate salary?",MCQ,"Very comfortable, Somewhat, Prefer steady salary",Domain Preference: Creative Arts & Media,career_pref_creative_arts_media_q113,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
113,Q114,Education & Career Preferences,Are you able to separate your personal ego from your work when a client demands heavy revisions?,MCQ,"Yes easily, Sometimes difficult, No",Domain Preference: Creative Arts & Media,career_pref_creative_arts_media_q114,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
114,Q115,Education & Career Preferences,Do you prefer working solo in a studio or on a bustling set with a large production crew?,MCQ,"Solo, Large crew",Domain Preference: Creative Arts & Media,career_pref_creative_arts_media_q115,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
115,Q116,Education & Career Preferences,Do you prefer arguing cases in a courtroom or drafting contracts and advising behind the scenes?,MCQ,"Courtroom/Litigation, Corporate/Drafting, N/A",Domain Preference: Law & Public Service,career_pref_law_public_service_q116,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
116,Q117,Education & Career Preferences,How important is it for your work to directly influence public policy or government administration?,MCQ,"Very important, Somewhat, Not important",Domain Preference: Law & Public Service,career_pref_law_public_service_q117,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
117,Q118,Education & Career Preferences,Are you comfortable defending clients or policies that you personally disagree with?,MCQ,"Yes, No, Depends on the issue",Domain Preference: Law & Public Service,career_pref_law_public_service_q118,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
118,Q119,Education & Career Preferences,Do you prefer the fast pace of a corporate law firm or the stability of government/public sector work?,MCQ,"Corporate Law Firm, Government/Public Sector, NGO/Non-profit",Domain Preference: Law & Public Service,career_pref_law_public_service_q119,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
119,Q120,Education & Career Preferences,How comfortable are you reading and synthesizing hundreds of pages of dense legal precedent daily?,MCQ,"Very comfortable, Somewhat, Uncomfortable",Domain Preference: Law & Public Service,career_pref_law_public_service_q120,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring

## Step 9 — Resolve the 12 missing feature mappings

In [18]:

# Step 9A: Fill the 12 missing feature mappings

from pathlib import Path
import pandas as pd

PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

mapping_path = PROJECT_DIR / "Question_Mapping_All_120.csv"
mapping_120 = pd.read_csv(mapping_path)

# Proposed mappings for the 12 previously unmapped questions.
# These are provisional and must be checked against each question's wording.
missing_feature_mapping = {
    "Q009": (
        "interest_finance",
        "Interest rating 1-5",
        "Proposed; validate against question wording"
    ),
    "Q021": (
        "trait_teamwork",
        "Agreement rating 1-5; confirm item direction",
        "Proposed new feature; review wording"
    ),
    "Q022": (
        "trait_agreeableness",
        "Agreement rating 1-5; reverse-score only if warranted",
        "Proposed; verify trait and item direction"
    ),
    "Q027": (
        "trait_rule_adherence",
        "Agreement rating 1-5; confirm item direction",
        "Proposed new feature; review wording"
    ),
    "Q029": (
        "trait_analytical_thinking",
        "Agreement rating 1-5; confirm construct",
        "Proposed new feature; validate construct"
    ),
    "Q030": (
        "trait_adaptability",
        "Agreement rating 1-5; confirm item direction",
        "Proposed new feature; review wording"
    ),
    "Q033": (
        "skill_design",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
    "Q034": (
        "skill_finance",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
    "Q035": (
        "skill_cybersecurity",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
    "Q037": (
        "skill_marketing",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
    "Q038": (
        "skill_legal_policy",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
    "Q039": (
        "skill_engineering",
        "Skill rating 1-5; N/A remains missing",
        "Proposed new feature; validate wording"
    ),
}

for qid, (feature, scoring, status) in missing_feature_mapping.items():
    mask = mapping_120["Question_ID"].eq(qid)

    if not mask.any():
        print(f"WARNING: {qid} not found in mapping table.")
        continue

    # Fill only missing features; do not overwrite existing mappings.
    missing_mask = mask & mapping_120["Proposed_Feature"].isna()

    mapping_120.loc[missing_mask, "Proposed_Feature"] = feature
    mapping_120.loc[missing_mask, "Proposed_Scoring_Method"] = scoring
    mapping_120.loc[missing_mask, "Mapping_Status"] = status

# Validate and save
mapping_120.to_csv(mapping_path, index=False, encoding="utf-8-sig")

print("Total questions:", len(mapping_120))
print("Unique question IDs:", mapping_120["Question_ID"].nunique())
print("Missing feature mappings:", mapping_120["Proposed_Feature"].isna().sum())
print("Questions still requiring review:",
      mapping_120["Mapping_Status"].astype(str).str.contains(
          "review|validat|verify|confirm", case=False, regex=True
      ).sum())

display(
    mapping_120[
        mapping_120["Question_ID"].isin(missing_feature_mapping)
    ][[
        "Question_ID", "Question_Text", "Proposed_Feature",
        "Proposed_Scoring_Method", "Mapping_Status"
    ]].sort_values("Question_ID")
)

print("\nUpdated file:", mapping_path)

Total questions: 120
Unique question IDs: 120
Missing feature mappings: 0
Questions still requiring review: 106

,Question_ID,Question_Text,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
8,Q009,"How interested are you in auditing financial records, calculating risk, and forecasting company revenue?",interest_finance,Interest rating 1-5,Proposed; validate against question wording
20,Q021,I thrive in environments where I must collaborate closely with a diverse team to achieve a shared goal.,trait_teamwork,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
21,Q022,"I prefer structured environments with clear guidelines over ambiguous, open-ended tasks.",trait_agreeableness,Agreement rating 1-5; reverse-score only if warranted,Proposed; verify trait and item direction
26,Q027,I prefer to follow established rules and protocols rather than breaking conventions to find a faster shortcut.,trait_rule_adherence,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
28,Q029,I tend to rely on logical analysis and objective facts rather than intuition when making important decisions.,trait_analytical_thinking,Agreement rating 1-5; confirm construct,Proposed new feature; validate construct
29,Q030,"I am comfortable abandoning a project I've worked hard on if a better, entirely different solution is proposed.",trait_adaptability,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
32,Q033,"How would you rate your proficiency with design software (e.g., Figma, Adobe Creative Suite)?",skill_design,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
33,Q034,How would you rate your ability to read financial statements and perform financial modeling?,skill_finance,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
34,Q035,"How would you rate your ability to configure firewalls, identify malware, or apply encryption standards?",skill_cybersecurity,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
36,Q037,How would you rate your ability to set up targeted advertising campaigns or perform SEO?,skill_marketing,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
37,Q038,"How would you rate your ability to comprehend complex legal texts, draft contracts, or navigate compliance?",skill_legal_policy,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
38,Q039,"How would you rate your proficiency with core engineering tools (e.g., CAD software)?",skill_engineering,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording

Updated file: C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset\Question_Mapping_All_120.csv

## Step 10A — Audit the synthetic dataset

In [19]:

# Step 10A: Dataset audit and feature-scale validation

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset"
)

# Correct Q022's provisional feature mapping
mapping_path = PROJECT_DIR / "Question_Mapping_All_120.csv"
mapping_120 = pd.read_csv(mapping_path)

mask = mapping_120["Question_ID"].eq("Q022")
mapping_120.loc[mask, "Proposed_Feature"] = "trait_structure_preference"
mapping_120.loc[mask, "Mapping_Status"] = (
    "Proposed; construct-specific, not a direct Big Five agreeableness measure"
)
mapping_120.to_csv(mapping_path, index=False, encoding="utf-8-sig")

# Load datasets
file_names = {
    "processed": "career_guidance_processed.csv",
    "train": "career_guidance_train.csv",
    "test": "career_guidance_test.csv",
}

datasets = {}

for name, filename in file_names.items():
    path = PROJECT_DIR / filename
    if path.exists():
        datasets[name] = pd.read_csv(path)
        print(f"\n{name.upper()} DATASET")
        print("File:", filename)
        print("Shape:", datasets[name].shape)
        print("Columns:", datasets[name].columns.tolist())
    else:
        print(f"\nWARNING: File not found: {path}")

# Check target distribution
target = "recommended_career_domain"

for name, df in datasets.items():
    print(f"\n--- {name.upper()}: TARGET DISTRIBUTION ---")
    if target in df.columns:
        print(df[target].value_counts(dropna=False).to_string())
    else:
        print(f"Target column '{target}' is missing.")

# Audit the 21 original assessment features
assessment_features = [
    "interest_technology", "interest_data",
    "interest_problem_solving", "interest_creativity",
    "interest_people", "interest_helping",
    "aptitude_logical", "aptitude_numerical",
    "aptitude_verbal", "aptitude_spatial",
    "aptitude_critical_thinking",
    "trait_openness", "trait_conscientiousness",
    "trait_extraversion", "trait_agreeableness",
    "trait_emotional_stability",
    "skill_programming", "skill_data_analysis",
    "skill_research", "skill_communication",
    "skill_leadership",
]

for name, df in datasets.items():
    print(f"\n--- {name.upper()}: ASSESSMENT FEATURE AUDIT ---")

    present = [c for c in assessment_features if c in df.columns]
    missing = [c for c in assessment_features if c not in df.columns]

    print("Expected features present:", len(present), "/", len(assessment_features))
    print("Missing features:", missing if missing else "None")

    if present:
        numeric = df[present].apply(pd.to_numeric, errors="coerce")
        summary = pd.DataFrame({
            "dtype": df[present].dtypes.astype(str),
            "min": numeric.min(),
            "max": numeric.max(),
            "mean": numeric.mean(),
            "missing_count": numeric.isna().sum(),
            "unique_values": numeric.nunique(),
        })
        display(summary)

# Check for profile ID overlap between train and test
if "train" in datasets and "test" in datasets:
    train_df = datasets["train"]
    test_df = datasets["test"]

    if "profile_id" in train_df.columns and "profile_id" in test_df.columns:
        overlap = set(train_df["profile_id"].dropna()) & set(
            test_df["profile_id"].dropna()
        )
        print("\nTrain/test profile ID overlap:", len(overlap))
    else:
        print("\nProfile ID overlap not checked: profile_id is absent.")

print("\nAudit complete. No dataset values were modified.")

PROCESSED DATASET
File: career_guidance_processed.csv
Shape: (2400, 27)
Columns: ['profile_id', 'age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']

TRAIN DATASET
File: career_guidance_train.csv
Shape: (1920, 26)
Columns: ['age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']

TEST DATASET
File: career_guidance_test.csv
Shape: (480, 26)
Columns: ['age_group', 'education_level', 'experience_stage', 'region_type', 'interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership', 'recommended_career_domain']

--- PROCESSED: TARGET DISTRIBUTION ---
recommended_career_domain
UI/UX Design                     211
Law & Public Service             208
Education & Research             207
Healthcare & Life Sciences       207
Software Development             205
Data Science & Analytics         201
Engineering & Core Technology    200
Business & Management            200
Digital Marketing                196
Finance & Accounting             189
Creative Arts & Media            189
Cybersecurity                    187

--- TRAIN: TARGET DISTRIBUTION ---
recommended_career_domain
UI/UX Design                     169
Education & Research             166
Law & Public Service             166
Healthcare & Life Sciences       166
Software Development             164
Data Science & Analytics         161
Engineering & Core Technology    160
Business & Management            160
Digital Marketing                157
Finance & Accounting             151
Creative Arts & Media            151
Cybersecurity                    149

--- TEST: TARGET DISTRIBUTION ---
recommended_career_domain
Law & Public Service             42
UI/UX Design                     42
Healthcare & Life Sciences       41
Software Development             41
Education & Research             41
Engineering & Core Technology    40
Business & Management            40
Data Science & Analytics         40
Digital Marketing                39
Cybersecurity                    38
Creative Arts & Media            38
Finance & Accounting             38

--- PROCESSED: ASSESSMENT FEATURE AUDIT ---
Expected features present: 21 / 21
Missing features: None

                              dtype       min  max      mean  missing_count  unique_values
interest_technology         float64  0.033333  1.0  0.699741              0             81
interest_data               float64  0.000000  1.0  0.657940              0             87
interest_problem_solving    float64  0.011111  1.0  0.702843              0             79
interest_creativity         float64  0.000000  1.0  0.685657              0             83
interest_people             float64  0.000000  1.0  0.708509              0             83
interest_helping            float64  0.000000  1.0  0.601139              0             91
aptitude_logical            float64  0.088889  1.0  0.760958              0             71
aptitude_numerical          float64  0.122222  1.0  0.724569              0             78
aptitude_verbal             float64  0.166667  1.0  0.700315              0             76
aptitude_spatial            float64  0.088889  1.0  0.727620              0             72
aptitude_critical_thinking  float64  0.111111  1.0  0.702912              0             76
trait_openness              float64  0.166667  1.0  0.719046              0             69
trait_conscientiousness     float64  0.222222  1.0  0.733389              0             69
trait_extraversion          float64  0.111111  1.0  0.699875              0             80
trait_agreeableness         float64  0.100000  1.0  0.725495              0             73
trait_emotional_stability   float64  0.100000  1.0  0.679144              0             80
skill_programming           float64  0.000000  1.0  0.635074              0             84
skill_data_analysis         float64  0.000000  1.0  0.636120              0             88
skill_research              float64  0.000000  1.0  0.576764              0             89
skill_communication         float64  0.033333  1.0  0.725236              0             79
skill_leadership            float64  0.000000  1.0  0.683704              0             88

--- TRAIN: ASSESSMENT FEATURE AUDIT ---
Expected features present: 21 / 21
Missing features: None

                              dtype  min   max      mean  missing_count  unique_values
interest_technology         float64  1.3  10.0  7.306250              0             80
interest_data               float64  1.0  10.0  6.939688              0             85
interest_problem_solving    float64  1.1  10.0  7.353385              0             77
interest_creativity         float64  1.0  10.0  7.177969              0             83
interest_people             float64  1.0  10.0  7.407552              0             78
interest_helping            float64  1.0  10.0  6.423490              0             90
aptitude_logical            float64  1.8  10.0  7.851458              0             71
aptitude_numerical          float64  2.1  10.0  7.505885              0             76
aptitude_verbal             float64  2.5  10.0  7.266510              0             76
aptitude_spatial            float64  2.7  10.0  7.563646              0             70
aptitude_critical_thinking  float64  2.3  10.0  7.340729              0             73
trait_openness              float64  3.0  10.0  7.470469              0             67
trait_conscientiousness     float64  3.2  10.0  7.608594              0             68
trait_extraversion          float64  2.0  10.0  7.293854              0             78
trait_agreeableness         float64  1.9  10.0  7.532604              0             73
trait_emotional_stability   float64  1.9  10.0  7.110833              0             77
skill_programming           float64  1.0  10.0  6.754531              0             83
skill_data_analysis         float64  1.0  10.0  6.723542              0             88
skill_research              float64  1.0  10.0  6.195052              0             89
skill_communication         float64  1.3  10.0  7.548802              0             78
skill_leadership            float64  1.0  10.0  7.172187              0             87

--- TEST: ASSESSMENT FEATURE AUDIT ---
Expected features present: 21 / 21
Missing features: None

                              dtype  min   max      mean  missing_count  unique_values
interest_technology         float64  1.9  10.0  7.263333              0             72
interest_data               float64  1.4  10.0  6.848542              0             78
interest_problem_solving    float64  1.4  10.0  7.214375              0             71
interest_creativity         float64  1.8  10.0  7.142708              0             77
interest_people             float64  1.5  10.0  7.252708              0             74
interest_helping            float64  1.2  10.0  6.357292              0             84
aptitude_logical            float64  3.7  10.0  7.837292              0             58
aptitude_numerical          float64  2.3  10.0  7.582083              0             68
aptitude_verbal             float64  2.7  10.0  7.448125              0             67
aptitude_spatial            float64  1.8  10.0  7.488333              0             65
aptitude_critical_thinking  float64  2.0  10.0  7.268125              0             66
trait_openness              float64  2.5  10.0  7.475208              0             64
trait_conscientiousness     float64  3.0  10.0  7.568125              0             63
trait_extraversion          float64  2.1  10.0  7.318958              0             68
trait_agreeableness         float64  3.2  10.0  7.516875              0             60
trait_emotional_stability   float64  2.0  10.0  7.118125              0             71
skill_programming           float64  1.6  10.0  6.560208              0             76
skill_data_analysis         float64  1.0  10.0  6.731250              0             83
skill_research              float64  1.2  10.0  6.174167              0             81
skill_communication         float64  2.4  10.0  7.440417              0             66
skill_leadership            float64  1.4  10.0  7.077917              0             80

Profile ID overlap not checked: profile_id is absent.

Audit complete. No dataset values were modified.

## 3. Step 10B — Verify whether the datasets are genuinely aligned

In [22]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

BASE_DIR = Path.cwd()

processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")
train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")
test = pd.read_csv(BASE_DIR / "career_guidance_test.csv")
mapping = pd.read_csv(BASE_DIR / "Question_Mapping_All_120.csv")

# Combine training and test data for comparison only
combined = pd.concat([train, test], ignore_index=True)

target = "recommended_career_domain"

features = [
    c for c in processed.columns
    if c in combined.columns and c != target
    and pd.api.types.is_numeric_dtype(processed[c])
    and pd.api.types.is_numeric_dtype(combined[c])
]

print("=" * 70)
print("1. ROW AND COLUMN CHECK")
print("Processed rows:", len(processed))
print("Combined train + test rows:", len(combined))
print("Processed-only columns:",
      sorted(set(processed.columns) - set(combined.columns)))
print("Train/test-only columns:",
      sorted(set(combined.columns) - set(processed.columns)))

print("\n2. TARGET LABEL CHECK")
print("Processed-only labels:",
      sorted(set(processed[target].dropna()) -
             set(combined[target].dropna())))
print("Train/test-only labels:",
      sorted(set(combined[target].dropna()) -
             set(processed[target].dropna())))

print("\nClass counts: processed vs combined train/test")
print(pd.concat([
    processed[target].value_counts().rename("processed"),
    combined[target].value_counts().rename("train_test_combined")
], axis=1).fillna(0).astype(int))

# Compare distributions after testing a possible scale conversion
rows = []

for feature in features:
    p = processed[feature].dropna()
    c = combined[feature].dropna()

    # Test whether processed values may correspond to a 0-1 scale
    # while train/test values use a 0-10 scale.
    p_scaled = p * 10

    rows.append({
        "feature": feature,
        "processed_min": p.min(),
        "processed_max": p.max(),
        "train_test_min": c.min(),
        "train_test_max": c.max(),
        "processed_mean_x10": p_scaled.mean(),
        "train_test_mean": c.mean(),
        "mean_difference_after_x10": abs(p_scaled.mean() - c.mean()),
        "processed_median_x10": p_scaled.median(),
        "train_test_median": c.median(),
    })

comparison = pd.DataFrame(rows)

print("\n3. FEATURE DISTRIBUTION COMPARISON")
print(comparison.round(3).to_string(index=False))

print("\n4. QUESTIONNAIRE FEATURE COVERAGE")
mapped = set(mapping["Feature_Mapping"].dropna().astype(str))
dataset_features = set(combined.columns) - {target}

print("Unique mapped questionnaire features:", len(mapped))
print("Mapped features already in ML dataset:",
      len(mapped & dataset_features))
print("Mapped features absent from ML dataset:",
      len(mapped - dataset_features))

print("\nAbsent mapped features:")
print(sorted(mapped - dataset_features))

# Inspect data dictionary without modifying it
dictionary_path = BASE_DIR / "data_dictionary.json"

if dictionary_path.exists():
    with open(dictionary_path, "r", encoding="utf-8") as f:
        dictionary = json.load(f)

    print("\n5. DATA DICTIONARY STRUCTURE")
    print("Top-level type:", type(dictionary).__name__)

    if isinstance(dictionary, dict):
        print("Top-level keys:", list(dictionary.keys()))

print("\nAudit complete. No files modified.")

======================================================================
1. ROW AND COLUMN CHECK
Processed rows: 2400
Combined train + test rows: 2400
Processed-only columns: ['profile_id']
Train/test-only columns: []

2. TARGET LABEL CHECK
Processed-only labels: []
Train/test-only labels: []

Class counts: processed vs combined train/test
                               processed  train_test_combined
recommended_career_domain
UI/UX Design                         211                  211
Law & Public Service                 208                  208
Education & Research                 207                  207
Healthcare & Life Sciences           207                  207
Software Development                 205                  205
Data Science & Analytics             201                  201
Engineering & Core Technology        200                  200
Business & Management                200                  200
Digital Marketing                    196                  196
Finance & Accounting                 189                  189
Creative Arts & Media                189                  189
Cybersecurity                        187                  187

3. FEATURE DISTRIBUTION COMPARISON
                   feature  processed_min  processed_max  train_test_min  train_test_max  processed_mean_x10  train_test_mean  mean_difference_after_x10  processed_median_x10  train_test_median
       interest_technology          0.033            1.0             1.3            10.0               6.997            7.298                      0.300                 7.000               7.30
             interest_data          0.000            1.0             1.0            10.0               6.579            6.921                      0.342                 6.556               6.90
  interest_problem_solving          0.011            1.0             1.1            10.0               7.028            7.326                      0.297                 7.000               7.30
       interest_creativity          0.000            1.0             1.0            10.0               6.857            7.171                      0.314                 6.889               7.20
           interest_people          0.000            1.0             1.0            10.0               7.085            7.377                      0.291                 7.222               7.50
          interest_helping          0.000            1.0             1.0            10.0               6.011            6.410                      0.399                 5.944               6.35
          aptitude_logical          0.089            1.0             1.8            10.0               7.610            7.849                      0.239                 7.667               7.90
        aptitude_numerical          0.122            1.0             2.1            10.0               7.246            7.521                      0.275                 7.333               7.60
           aptitude_verbal          0.167            1.0             2.5            10.0               7.003            7.303                      0.300                 7.000               7.30
          aptitude_spatial          0.089            1.0             1.8            10.0               7.276            7.549                      0.272                 7.333               7.60
aptitude_critical_thinking          0.111            1.0             2.0            10.0               7.029            7.326                      0.297                 7.111               7.40
            trait_openness          0.167            1.0             2.5            10.0               7.190            7.471                      0.281                 7.222               7.50
   trait_conscientiousness          0.222            1.0             3.0            10.0               7.334            7.600                      0.267                 7.333               7.60
        trait_extraversion          0.111            1.0             2.0            10.0               6.999            7.299                      0.300                 7.111               7.40
       trait_agreeableness          0.100            1.0             1.9            10.0               7.255            7.529                      0.275                 7.278               7.55
 trait_emotional_stability          0.100            1.0             1.9            10.0               6.791            7.112                      0.321                 6.778               7.10
         skill_programming          0.000            1.0             1.0            10.0               6.351            6.716                      0.365                 6.333               6.70
       skill_data_analysis          0.000            1.0             1.0            10.0               6.361            6.725                      0.364                 6.333               6.70
            skill_research          0.000            1.0             1.0            10.0               5.768            6.191                      0.423                 5.667               6.10
       skill_communication          0.033            1.0             1.3            10.0               7.252            7.527                      0.275                 7.444               7.70
          skill_leadership          0.000            1.0             1.0            10.0               6.837            7.153                      0.316                 7.000               7.30

4. QUESTIONNAIRE FEATURE COVERAGE

KeyError: 'Feature_Mapping'

## Step 10C — Inspect and fix the mapping-file column issue

In [21]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

mapping_path = BASE_DIR / "Question_Mapping_All_120.csv"

print("Mapping file exists:", mapping_path.exists())
print("Mapping file path:", mapping_path)

if mapping_path.exists():
    mapping = pd.read_csv(mapping_path, encoding="utf-8-sig")

    # Remove accidental spaces from column headers
    mapping.columns = mapping.columns.astype(str).str.strip()

    print("\nActual mapping columns:")
    print([repr(c) for c in mapping.columns])

    print("\nFirst five rows:")
    display(mapping.head())

    print("\nPossible feature-mapping columns:")
    print([
        c for c in mapping.columns
        if "feature" in c.lower() or "mapping" in c.lower()
    ])

else:
    print("\nMapping files found in the dataset directory:")
    for path in BASE_DIR.glob("*Mapping*.csv"):
        print(path.name)

Mapping file exists: True
Mapping file path: C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT\AI_Career_Guidance_Dataset_Package\AI_Career_Guidance_Dataset\Question_Mapping_All_120.csv

Actual mapping columns:
["'Question_ID'", "'Section'", "'Question_Text'", "'Answer_Type'", "'Answer_Options'", "'Purpose'", "'Proposed_Feature'", "'Proposed_Scoring_Method'", "'Mapping_Status'"]

First five rows:

,Question_ID,Section,Question_Text,Answer_Type,Answer_Options,Purpose,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
0,Q001,Interest,"How interested are you in writing scripts or code to automate complex, repetitive tasks?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in core programming and logic,interest_technology,Rating 1-5,Proposed
1,Q002,Interest,How interested are you in analyzing large datasets to identify hidden trends and predict future outcomes?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in data science and statistical analysis,interest_data,Rating 1-5,Proposed
2,Q003,Interest,How interested are you in finding vulnerabilities in computer networks and systems to prevent unauthorized access?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in cybersecurity and risk mitigation,interest_technology,Rating 1-5,Proxy; review
3,Q004,Interest,How interested are you in sketching out wireframes and designing the visual layout of a mobile application?,Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in UI/UX and user-centric design,interest_creativity,Rating 1-5,Proxy; review
4,Q005,Interest,"How interested are you in coordinating team members, managing budgets, and overseeing a project from start to finish?",Rating scale (1-5),1 - Not interested at all to 5 - Extremely interested,Measures interest in business management and leadership,interest_people,Rating 1-5,Proxy; review

Possible feature-mapping columns:
['Proposed_Feature', 'Mapping_Status']

In [23]:
from pathlib import Path
import pandas as pd

# 1. Set the correct project directory
BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

# 2. Load mapping and datasets
mapping = pd.read_csv(
    BASE_DIR / "Question_Mapping_All_120.csv",
    encoding="utf-8-sig"
)

processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")
train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")
test = pd.read_csv(BASE_DIR / "career_guidance_test.csv")

# 3. Clean column names
for df in [mapping, processed, train, test]:
    df.columns = df.columns.astype(str).str.strip()

# 4. Use the actual column name from your CSV
feature_column = "Proposed_Feature"

mapping[feature_column] = mapping[feature_column].fillna("").astype(str).str.strip()

# Remove empty feature mappings
valid_mapping = mapping[
    mapping[feature_column].ne("")
].copy()

mapped_features = set(valid_mapping[feature_column])
processed_features = set(processed.columns)
train_features = set(train.columns)
test_features = set(test.columns)

# 5. Compare mapped features with dataset columns
print("=" * 65)
print("QUESTIONNAIRE FEATURE COVERAGE AUDIT")
print("=" * 65)

print("Total questionnaire rows:", len(mapping))
print("Questions with proposed features:", len(valid_mapping))
print("Questions without proposed features:",
      (mapping[feature_column] == "").sum())

print("\nUnique proposed feature names:", len(mapped_features))

print("\n--- Proposed features missing from processed dataset ---")
missing_processed = sorted(mapped_features - processed_features)
print(missing_processed if missing_processed else "None")

print("\n--- Proposed features missing from training dataset ---")
missing_train = sorted(mapped_features - train_features)
print(missing_train if missing_train else "None")

print("\n--- Proposed features missing from test dataset ---")
missing_test = sorted(mapped_features - test_features)
print(missing_test if missing_test else "None")

# 6. Review mapping statuses
print("\n--- Mapping status counts ---")
display(mapping["Mapping_Status"].value_counts(dropna=False).to_frame())

# 7. Show every question whose proposed feature is absent
missing_rows = mapping[
    mapping[feature_column].ne("")
    & ~mapping[feature_column].isin(processed_features)
][
    ["Question_ID", "Section", "Question_Text",
     "Proposed_Feature", "Proposed_Scoring_Method", "Mapping_Status"]
]

print("\n--- Questions mapped to features absent from the processed dataset ---")
display(missing_rows)

# 8. Save the audit output for later review
missing_rows.to_csv(
    BASE_DIR / "Step_10C_Missing_Feature_Mappings.csv",
    index=False
)

print("\nAudit saved to Step_10C_Missing_Feature_Mappings.csv")

=================================================================
QUESTIONNAIRE FEATURE COVERAGE AUDIT
=================================================================
Total questionnaire rows: 120
Questions with proposed features: 120
Questions without proposed features: 0

Unique proposed feature names: 109

--- Proposed features missing from processed dataset ---
['career_pref_business_management_q081', 'career_pref_business_management_q082', 'career_pref_business_management_q083', 'career_pref_business_management_q084', 'career_pref_business_management_q085', 'career_pref_creative_arts_media_q111', 'career_pref_creative_arts_media_q112', 'career_pref_creative_arts_media_q113', 'career_pref_creative_arts_media_q114', 'career_pref_creative_arts_media_q115', 'career_pref_cybersecurity_q071', 'career_pref_cybersecurity_q072', 'career_pref_cybersecurity_q073', 'career_pref_cybersecurity_q074', 'career_pref_cybersecurity_q075', 'career_pref_data_science_q066', 'career_pref_data_science_q067', 'career_pref_data_science_q068', 'career_pref_data_science_q069', 'career_pref_data_science_q070', 'career_pref_digital_marketing_q096', 'career_pref_digital_marketing_q097', 'career_pref_digital_marketing_q098', 'career_pref_digital_marketing_q099', 'career_pref_digital_marketing_q100', 'career_pref_education_research_q091', 'career_pref_education_research_q092', 'career_pref_education_research_q093', 'career_pref_education_research_q094', 'career_pref_education_research_q095', 'career_pref_engineering_technology_q106', 'career_pref_engineering_technology_q107', 'career_pref_engineering_technology_q108', 'career_pref_engineering_technology_q109', 'career_pref_engineering_technology_q110', 'career_pref_finance_accounting_q101', 'career_pref_finance_accounting_q102', 'career_pref_finance_accounting_q103', 'career_pref_finance_accounting_q104', 'career_pref_finance_accounting_q105', 'career_pref_healthcare_q086', 'career_pref_healthcare_q087', 'career_pref_healthcare_q088', 'career_pref_healthcare_q089', 'career_pref_healthcare_q090', 'career_pref_law_public_service_q116', 'career_pref_law_public_service_q117', 'career_pref_law_public_service_q118', 'career_pref_law_public_service_q119', 'career_pref_law_public_service_q120', 'career_pref_software_development_q061', 'career_pref_software_development_q062', 'career_pref_software_development_q063', 'career_pref_software_development_q064', 'career_pref_software_development_q065', 'career_pref_ui_ux_design_q076', 'career_pref_ui_ux_design_q077', 'career_pref_ui_ux_design_q078', 'career_pref_ui_ux_design_q079', 'career_pref_ui_ux_design_q080', 'interest_finance', 'profile_academic_field', 'profile_academic_performance', 'profile_certification_status', 'profile_company_size_preference', 'profile_education_level', 'profile_five_year_goal', 'profile_freelance_business_experience', 'profile_internship_experience', 'profile_leadership_experience', 'profile_minimum_salary_expectation', 'profile_performance_evaluation_preference', 'profile_primary_career_motivation', 'profile_relocation_willingness', 'profile_stability_growth_preference', 'profile_team_size_experience', 'profile_training_duration', 'profile_travel_willingness', 'profile_work_environment', 'profile_work_experience', 'profile_work_schedule_preference', 'skill_cybersecurity', 'skill_design', 'skill_engineering', 'skill_finance', 'skill_legal_policy', 'skill_marketing', 'trait_adaptability', 'trait_analytical_thinking', 'trait_rule_adherence', 'trait_structure_preference', 'trait_teamwork']

--- Proposed features missing from training dataset ---
['career_pref_business_management_q081', 'career_pref_business_management_q082', 'career_pref_business_management_q083', 'career_pref_business_management_q084', 'career_pref_business_management_q085', 'career_pref_creative_arts_media_q111', 'career_pref_creative_arts_media_q112', 'career_pref_creative_arts_media_q113', 'career_pref_creative_arts_media_q114', 'career_pref_creative_arts_media_q115', 'career_pref_cybersecurity_q071', 'career_pref_cybersecurity_q072', 'career_pref_cybersecurity_q073', 'career_pref_cybersecurity_q074', 'career_pref_cybersecurity_q075', 'career_pref_data_science_q066', 'career_pref_data_science_q067', 'career_pref_data_science_q068', 'career_pref_data_science_q069', 'career_pref_data_science_q070', 'career_pref_digital_marketing_q096', 'career_pref_digital_marketing_q097', 'career_pref_digital_marketing_q098', 'career_pref_digital_marketing_q099', 'career_pref_digital_marketing_q100', 'career_pref_education_research_q091', 'career_pref_education_research_q092', 'career_pref_education_research_q093', 'career_pref_education_research_q094', 'career_pref_education_research_q095', 'career_pref_engineering_technology_q106', 'career_pref_engineering_technology_q107', 'career_pref_engineering_technology_q108', 'career_pref_engineering_technology_q109', 'career_pref_engineering_technology_q110', 'career_pref_finance_accounting_q101', 'career_pref_finance_accounting_q102', 'career_pref_finance_accounting_q103', 'career_pref_finance_accounting_q104', 'career_pref_finance_accounting_q105', 'career_pref_healthcare_q086', 'career_pref_healthcare_q087', 'career_pref_healthcare_q088', 'career_pref_healthcare_q089', 'career_pref_healthcare_q090', 'career_pref_law_public_service_q116', 'career_pref_law_public_service_q117', 'career_pref_law_public_service_q118', 'career_pref_law_public_service_q119', 'career_pref_law_public_service_q120', 'career_pref_software_development_q061', 'career_pref_software_development_q062', 'career_pref_software_development_q063', 'career_pref_software_development_q064', 'career_pref_software_development_q065', 'career_pref_ui_ux_design_q076', 'career_pref_ui_ux_design_q077', 'career_pref_ui_ux_design_q078', 'career_pref_ui_ux_design_q079', 'career_pref_ui_ux_design_q080', 'interest_finance', 'profile_academic_field', 'profile_academic_performance', 'profile_certification_status', 'profile_company_size_preference', 'profile_education_level', 'profile_five_year_goal', 'profile_freelance_business_experience', 'profile_internship_experience', 'profile_leadership_experience', 'profile_minimum_salary_expectation', 'profile_performance_evaluation_preference', 'profile_primary_career_motivation', 'profile_relocation_willingness', 'profile_stability_growth_preference', 'profile_team_size_experience', 'profile_training_duration', 'profile_travel_willingness', 'profile_work_environment', 'profile_work_experience', 'profile_work_schedule_preference', 'skill_cybersecurity', 'skill_design', 'skill_engineering', 'skill_finance', 'skill_legal_policy', 'skill_marketing', 'trait_adaptability', 'trait_analytical_thinking', 'trait_rule_adherence', 'trait_structure_preference', 'trait_teamwork']

--- Proposed features missing from test dataset ---
['career_pref_business_management_q081', 'career_pref_business_management_q082', 'career_pref_business_management_q083', 'career_pref_business_management_q084', 'career_pref_business_management_q085', 'career_pref_creative_arts_media_q111', 'career_pref_creative_arts_media_q112', 'career_pref_creative_arts_media_q113', 'career_pref_creative_arts_media_q114', 'career_pref_creative_arts_media_q115', 'career_pref_cybersecurity_q071', 'career_pref_cybersecurity_q072', 'career_pref_cybersecurity_q073', 'career_pref_cybersecurity_q074', 'career_pref_cybersecurity_q075', 'career_pref_data_science_q066', 'career_pref_data_science_q067', 'career_pref_data_science_q068', 'career_pref_data_science_q069', 'career_pref_data_science_q070', 'career_pref_digital_marketing_q096', 'career_pref_digital_marketing_q097', 'career_pref_digital_marketing_q098', 'career_pref_digital_marketing_q099', 'career_pref_digital_marketing_q100', 'career_pref_education_research_q091', 'career_pref_education_research_q092', 'career_pref_education_research_q093', 'career_pref_education_research_q094', 'career_pref_education_research_q095', 'career_pref_engineering_technology_q106', 'career_pref_engineering_technology_q107', 'career_pref_engineering_technology_q108', 'career_pref_engineering_technology_q109', 'career_pref_engineering_technology_q110', 'career_pref_finance_accounting_q101', 'career_pref_finance_accounting_q102', 'career_pref_finance_accounting_q103', 'career_pref_finance_accounting_q104', 'career_pref_finance_accounting_q105', 'career_pref_healthcare_q086', 'career_pref_healthcare_q087', 'career_pref_healthcare_q088', 'career_pref_healthcare_q089', 'career_pref_healthcare_q090', 'career_pref_law_public_service_q116', 'career_pref_law_public_service_q117', 'career_pref_law_public_service_q118', 'career_pref_law_public_service_q119', 'career_pref_law_public_service_q120', 'career_pref_software_development_q061', 'career_pref_software_development_q062', 'career_pref_software_development_q063', 'career_pref_software_development_q064', 'career_pref_software_development_q065', 'career_pref_ui_ux_design_q076', 'career_pref_ui_ux_design_q077', 'career_pref_ui_ux_design_q078', 'career_pref_ui_ux_design_q079', 'career_pref_ui_ux_design_q080', 'interest_finance', 'profile_academic_field', 'profile_academic_performance', 'profile_certification_status', 'profile_company_size_preference', 'profile_education_level', 'profile_five_year_goal', 'profile_freelance_business_experience', 'profile_internship_experience', 'profile_leadership_experience', 'profile_minimum_salary_expectation', 'profile_performance_evaluation_preference', 'profile_primary_career_motivation', 'profile_relocation_willingness', 'profile_stability_growth_preference', 'profile_team_size_experience', 'profile_training_duration', 'profile_travel_willingness', 'profile_work_environment', 'profile_work_experience', 'profile_work_schedule_preference', 'skill_cybersecurity', 'skill_design', 'skill_engineering', 'skill_finance', 'skill_legal_policy', 'skill_marketing', 'trait_adaptability', 'trait_analytical_thinking', 'trait_rule_adherence', 'trait_structure_preference', 'trait_teamwork']

--- Mapping status counts ---

                                                                           count
Mapping_Status
Proposed domain-preference feature; validate scoring                          60
Proposed profile feature; validate encoding                                   20
Answer key supplied                                                            9
Proxy; review                                                                  7
Proposed new feature; validate wording                                         6
Proposed                                                                       5
Proposed; review                                                               4
Proposed new feature; review wording                                           3
Proposed; validate against question wording                                    1
Answer key supplied; review wording                                            1
Proposed; construct-specific, not a direct Big Five agreeableness measure      1
Leadership proxy; review                                                       1
Proposed new feature; validate construct                                       1
Project management proxy; review                                               1

--- Questions mapped to features absent from the processed dataset ---

,Question_ID,Section,Question_Text,Proposed_Feature,Proposed_Scoring_Method,Mapping_Status
8,Q009,Interest,"How interested are you in auditing financial records, calculating risk, and forecasting company revenue?",interest_finance,Interest rating 1-5,Proposed; validate against question wording
20,Q021,Personality,I thrive in environments where I must collaborate closely with a diverse team to achieve a shared goal.,trait_teamwork,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
21,Q022,Personality,"I prefer structured environments with clear guidelines over ambiguous, open-ended tasks.",trait_structure_preference,Agreement rating 1-5; reverse-score only if warranted,"Proposed; construct-specific, not a direct Big Five agreeableness measure"
26,Q027,Personality,I prefer to follow established rules and protocols rather than breaking conventions to find a faster shortcut.,trait_rule_adherence,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
28,Q029,Personality,I tend to rely on logical analysis and objective facts rather than intuition when making important decisions.,trait_analytical_thinking,Agreement rating 1-5; confirm construct,Proposed new feature; validate construct
29,Q030,Personality,"I am comfortable abandoning a project I've worked hard on if a better, entirely different solution is proposed.",trait_adaptability,Agreement rating 1-5; confirm item direction,Proposed new feature; review wording
32,Q033,Skills,"How would you rate your proficiency with design software (e.g., Figma, Adobe Creative Suite)?",skill_design,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
33,Q034,Skills,How would you rate your ability to read financial statements and perform financial modeling?,skill_finance,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
34,Q035,Skills,"How would you rate your ability to configure firewalls, identify malware, or apply encryption standards?",skill_cybersecurity,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
36,Q037,Skills,How would you rate your ability to set up targeted advertising campaigns or perform SEO?,skill_marketing,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
37,Q038,Skills,"How would you rate your ability to comprehend complex legal texts, draft contracts, or navigate compliance?",skill_legal_policy,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
38,Q039,Skills,"How would you rate your proficiency with core engineering tools (e.g., CAD software)?",skill_engineering,Skill rating 1-5; N/A remains missing,Proposed new feature; validate wording
40,Q041,Education & Career Preferences,What is your current or most recently completed level of education?,profile_education_level,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
41,Q042,Education & Career Preferences,Which broad academic field does your primary degree or certification fall under?,profile_academic_field,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
42,Q043,Education & Career Preferences,What is your cumulative academic performance/GPA equivalent?,profile_academic_performance,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
43,Q044,Education & Career Preferences,Have you completed any specialized bootcamps or professional certifications outside of formal degrees?,profile_certification_status,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
44,Q045,Education & Career Preferences,How many total years of formal education/training do you have in your primary field of interest?,profile_training_duration,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
45,Q046,Education & Career Preferences,How many years of full-time professional work experience do you currently have?,profile_work_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
46,Q047,Education & Career Preferences,"Have you ever completed an internship, apprenticeship, or practical training program?",profile_internship_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
47,Q048,Education & Career Preferences,Have you ever held a leadership or management role where you were responsible for others?,profile_leadership_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
48,Q049,Education & Career Preferences,Do you have experience working as a freelancer or running your own business/startup?,profile_freelance_business_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
49,Q050,Education & Career Preferences,What is the largest team size you have consistently worked with?,profile_team_size_experience,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
50,Q051,Education & Career Preferences,What is your primary career motivation?,profile_primary_career_motivation,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
51,Q052,Education & Career Preferences,What is your minimum acceptable starting salary expectation (in your local currency/tier)?,profile_minimum_salary_expectation,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
52,Q053,Education & Career Preferences,Are you willing to relocate to a different city or country for the right career opportunity?,profile_relocation_willingness,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
53,Q054,Education & Career Preferences,Where do you see yourself in 5 years?,profile_five_year_goal,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
54,Q055,Education & Career Preferences,"How important is job security and stability compared to rapid, high-risk career growth?",profile_stability_growth_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
55,Q056,Education & Career Preferences,What is your preferred working environment?,profile_work_environment,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
56,Q057,Education & Career Preferences,Which company size do you prefer working for?,profile_company_size_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
57,Q058,Education & Career Preferences,Are you willing to travel frequently (more than 30% of the time) for work?,profile_travel_willingness,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
58,Q059,Education & Career Preferences,Do you prefer a predictable 9-to-5 schedule or flexible hours that may require occasional nights/weekends?,profile_work_schedule_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
59,Q060,Education & Career Preferences,How do you prefer to be evaluated at work?,profile_performance_evaluation_preference,Preserve selected category; encode categorically. Use ordinal encoding only when option order is meaningful.,Proposed profile feature; validate encoding
60,Q061,Education & Career Preferences,Which aspect of software development interests you the most?,career_pref_software_development_q061,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
61,Q062,Education & Career Preferences,Are you willing to participate in on-call rotations for emergency system outages?,career_pref_software_development_q062,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
62,Q063,Education & Career Preferences,Do you prefer building consumer-facing applications or internal enterprise tools?,career_pref_software_development_q063,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
63,Q064,Education & Career Preferences,How comfortable are you with continuous integration and rapid deployment cycles?,career_pref_software_development_q064,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
64,Q065,Education & Career Preferences,Which software ecosystem do you prefer working in?,career_pref_software_development_q065,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
65,Q066,Education & Career Preferences,Do you prefer building predictive machine learning models or creating dashboards/reports for business leaders?,career_pref_data_science_q066,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
66,Q067,Education & Career Preferences,"Are you comfortable dealing with messy, unstructured data that requires heavy cleaning?",career_pref_data_science_q067,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
67,Q068,Education & Career Preferences,Do you prefer deep-diving into a single complex algorithm or applying multiple standard algorithms rapidly?,career_pref_data_science_q068,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
68,Q069,Education & Career Preferences,"How important is it for you to work with cutting-edge AI technologies (e.g., LLMs, Computer Vision)?",career_pref_data_science_q069,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
69,Q070,Education & Career Preferences,Are you comfortable presenting complex statistical findings to non-technical stakeholders?,career_pref_data_science_q070,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
70,Q071,Education & Career Preferences,Do you prefer offensive security (Red Team/Penetration Testing) or defensive security (Blue Team/Incident Response)?,career_pref_cybersecurity_q071,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
71,Q072,Education & Career Preferences,Are you willing to undergo extensive background checks and maintain government security clearances?,career_pref_cybersecurity_q072,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
72,Q073,Education & Career Preferences,"How comfortable are you working in high-stress, time-critical incident response scenarios?",career_pref_cybersecurity_q073,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
73,Q074,Education & Career Preferences,"Do you prefer auditing policies and compliance, or actively hunting for technical vulnerabilities?",career_pref_cybersecurity_q074,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
74,Q075,Education & Career Preferences,Are you willing to continually study new threat vectors outside of standard work hours?,career_pref_cybersecurity_q075,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
75,Q076,Education & Career Preferences,"Do you prefer conducting user research (interviews, surveys) or creating high-fidelity visual designs?",career_pref_ui_ux_design_q076,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
76,Q077,Education & Career Preferences,How comfortable are you adapting your designs based on strict technical limitations from developers?,career_pref_ui_ux_design_q077,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
77,Q078,Education & Career Preferences,Do you prefer working on entirely new product concepts or optimizing existing legacy interfaces?,career_pref_ui_ux_design_q078,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
78,Q079,Education & Career Preferences,How important is establishing and maintaining a strict design system (component library) to you?,career_pref_ui_ux_design_q079,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
79,Q080,Education & Career Preferences,Are you comfortable defending your design choices to stakeholders using qualitative data?,career_pref_ui_ux_design_q080,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
80,Q081,Education & Career Preferences,"Do you prefer managing people (HR, team dynamics) or managing processes (Agile, supply chain)?",career_pref_business_management_q081,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
81,Q082,Education & Career Preferences,How comfortable are you taking responsibility for a project's financial profit and loss (P&L)?,career_pref_business_management_q082,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
82,Q083,Education & Career Preferences,Do you prefer strategizing long-term corporate visions or executing short-term operational goals?,career_pref_business_management_q083,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
83,Q084,Education & Career Preferences,Are you comfortable resolving interpersonal conflicts between team members on a regular basis?,career_pref_business_management_q084,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
84,Q085,Education & Career Preferences,"How important is having a clear, hierarchical path to executive leadership to you?",career_pref_business_management_q085,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
85,Q086,Education & Career Preferences,Do you prefer interacting directly with patients or working behind the scenes in a laboratory/research setting?,career_pref_healthcare_q086,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
86,Q087,Education & Career Preferences,"How comfortable are you dealing with bodily fluids, severe illnesses, or emergency medical trauma?",career_pref_healthcare_q087,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
87,Q088,Education & Career Preferences,"Are you willing to work irregular shifts, including nights, weekends, and holidays?",career_pref_healthcare_q088,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
88,Q089,Education & Career Preferences,Do you prefer clinical practice or biomedical research?,career_pref_healthcare_q089,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
89,Q090,Education & Career Preferences,How comfortable are you navigating strict healthcare regulations and medical documentation procedures?,career_pref_healthcare_q090,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
90,Q091,Education & Career Preferences,What age group do you most prefer teaching or designing educational content for?,career_pref_education_research_q091,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
91,Q092,Education & Career Preferences,Do you prefer lecturing in front of large groups or providing 1-on-1 mentorship?,career_pref_education_research_q092,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring
92,Q093,Education & Career Preferences,How important is tenure or long-term academic job security to your career plan?,career_pref_education_research_q093,Preserve selected option; one-hot encode nominal options or use justified ordinal encoding. Define domain weights later.,Proposed domain-preference feature; validate scoring

Audit saved to Step_10C_Missing_Feature_Mappings.csv

## Step 10D — Classify Features Before Changing the Dataset

In [24]:
# Step 10D: Feature classification and alignment report

import pandas as pd
from pathlib import Path

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

mapping = pd.read_csv(
    BASE_DIR / "Question_Mapping_All_120.csv",
    encoding="utf-8-sig"
)
processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")

mapping.columns = mapping.columns.str.strip()
processed.columns = processed.columns.str.strip()

feature_col = "Proposed_Feature"

# One row per unique proposed feature
feature_report = (
    mapping[["Question_ID", "Section", feature_col, "Mapping_Status"]]
    .drop_duplicates(subset=[feature_col])
    .copy()
)

feature_report["Exists_In_Processed_Dataset"] = (
    feature_report[feature_col].isin(processed.columns)
)

def classify_feature(feature):
    if feature.startswith("career_pref_"):
        return "Career preference"
    elif feature.startswith("profile_"):
        return "Student profile"
    elif feature.startswith("interest_"):
        return "Interest"
    elif feature.startswith("aptitude_"):
        return "Aptitude"
    elif feature.startswith("trait_"):
        return "Personality"
    elif feature.startswith("skill_"):
        return "Skills"
    else:
        return "Other"

feature_report["Feature_Group"] = feature_report[feature_col].apply(
    classify_feature
)

print("UNIQUE FEATURE COUNT:", len(feature_report))
print("\nFEATURE GROUP SUMMARY")
display(
    feature_report.groupby(
        ["Feature_Group", "Exists_In_Processed_Dataset"]
    ).size().unstack(fill_value=0)
)

print("\nFEATURES ALREADY AVAILABLE")
display(
    feature_report[feature_report["Exists_In_Processed_Dataset"]]
    [[feature_col, "Feature_Group"]]
)

print("\nFEATURES REQUIRING ALIGNMENT")
display(
    feature_report[~feature_report["Exists_In_Processed_Dataset"]]
    [[feature_col, "Feature_Group", "Question_ID", "Mapping_Status"]]
)

feature_report.to_csv(
    BASE_DIR / "Step_10D_Feature_Alignment_Report.csv",
    index=False
)

print("\nSaved: Step_10D_Feature_Alignment_Report.csv")

UNIQUE FEATURE COUNT: 109

FEATURE GROUP SUMMARY

Exists_In_Processed_Dataset  False  True
Feature_Group
Aptitude                         0      3
Career preference               60      0
Interest                         1      6
Personality                      5      4
Skills                           6      4
Student profile                 20      0

FEATURES ALREADY AVAILABLE

              Proposed_Feature Feature_Group
0          interest_technology      Interest
1                interest_data      Interest
3          interest_creativity      Interest
4              interest_people      Interest
5             interest_helping      Interest
9     interest_problem_solving      Interest
10          aptitude_numerical      Aptitude
11            aptitude_logical      Aptitude
14  aptitude_critical_thinking      Aptitude
22          trait_extraversion   Personality
23     trait_conscientiousness   Personality
24              trait_openness   Personality
25   trait_emotional_stability   Personality
30           skill_programming        Skills
31         skill_data_analysis        Skills
35            skill_leadership        Skills
39              skill_research        Skills

FEATURES REQUIRING ALIGNMENT

                              Proposed_Feature      Feature_Group Question_ID                                                             Mapping_Status
8                             interest_finance           Interest        Q009                                Proposed; validate against question wording
20                              trait_teamwork        Personality        Q021                                       Proposed new feature; review wording
21                  trait_structure_preference        Personality        Q022  Proposed; construct-specific, not a direct Big Five agreeableness measure
26                        trait_rule_adherence        Personality        Q027                                       Proposed new feature; review wording
28                   trait_analytical_thinking        Personality        Q029                                   Proposed new feature; validate construct
29                          trait_adaptability        Personality        Q030                                       Proposed new feature; review wording
32                                skill_design             Skills        Q033                                     Proposed new feature; validate wording
33                               skill_finance             Skills        Q034                                     Proposed new feature; validate wording
34                         skill_cybersecurity             Skills        Q035                                     Proposed new feature; validate wording
36                             skill_marketing             Skills        Q037                                     Proposed new feature; validate wording
37                          skill_legal_policy             Skills        Q038                                     Proposed new feature; validate wording
38                           skill_engineering             Skills        Q039                                     Proposed new feature; validate wording
40                     profile_education_level    Student profile        Q041                                Proposed profile feature; validate encoding
41                      profile_academic_field    Student profile        Q042                                Proposed profile feature; validate encoding
42                profile_academic_performance    Student profile        Q043                                Proposed profile feature; validate encoding
43                profile_certification_status    Student profile        Q044                                Proposed profile feature; validate encoding
44                   profile_training_duration    Student profile        Q045                                Proposed profile feature; validate encoding
45                     profile_work_experience    Student profile        Q046                                Proposed profile feature; validate encoding
46               profile_internship_experience    Student profile        Q047                                Proposed profile feature; validate encoding
47               profile_leadership_experience    Student profile        Q048                                Proposed profile feature; validate encoding
48       profile_freelance_business_experience    Student profile        Q049                                Proposed profile feature; validate encoding
49                profile_team_size_experience    Student profile        Q050                                Proposed profile feature; validate encoding
50           profile_primary_career_motivation    Student profile        Q051                                Proposed profile feature; validate encoding
51          profile_minimum_salary_expectation    Student profile        Q052                                Proposed profile feature; validate encoding
52              profile_relocation_willingness    Student profile        Q053                                Proposed profile feature; validate encoding
53                      profile_five_year_goal    Student profile        Q054                                Proposed profile feature; validate encoding
54         profile_stability_growth_preference    Student profile        Q055                                Proposed profile feature; validate encoding
55                    profile_work_environment    Student profile        Q056                                Proposed profile feature; validate encoding
56             profile_company_size_preference    Student profile        Q057                                Proposed profile feature; validate encoding
57                  profile_travel_willingness    Student profile        Q058                                Proposed profile feature; validate encoding
58            profile_work_schedule_preference    Student profile        Q059                                Proposed profile feature; validate encoding
59   profile_performance_evaluation_preference    Student profile        Q060                                Proposed profile feature; validate encoding
60       career_pref_software_development_q061  Career preference        Q061                       Proposed domain-preference feature; validate scoring
61       career_pref_software_development_q062  Career preference        Q062                       Proposed domain-preference feature; validate scoring
62       career_pref_software_development_q063  Career preference        Q063                       Proposed domain-preference feature; validate scoring
63       career_pref_software_development_q064  Career preference        Q064                       Proposed domain-preference feature; validate scoring
64       career_pref_software_development_q065  Career preference        Q065                       Proposed domain-preference feature; validate scoring
65               career_pref_data_science_q066  Career preference        Q066                       Proposed domain-preference feature; validate scoring
66               career_pref_data_science_q067  Career preference        Q067                       Proposed domain-preference feature; validate scoring
67               career_pref_data_science_q068  Career preference        Q068                       Proposed domain-preference feature; validate scoring
68               career_pref_data_science_q069  Career preference        Q069                       Proposed domain-preference feature; validate scoring
69               career_pref_data_science_q070  Career preference        Q070                       Proposed domain-preference feature; validate scoring
70              career_pref_cybersecurity_q071  Career preference        Q071                       Proposed domain-preference feature; validate scoring
71              career_pref_cybersecurity_q072  Career preference        Q072                       Proposed domain-preference feature; validate scoring
72              career_pref_cybersecurity_q073  Career preference        Q073                       Proposed domain-preference feature; validate scoring
73              career_pref_cybersecurity_q074  Career preference        Q074                       Proposed domain-preference feature; validate scoring
74              career_pref_cybersecurity_q075  Career preference        Q075                       Proposed domain-preference feature; validate scoring
75               career_pref_ui_ux_design_q076  Career preference        Q076                       Proposed domain-preference feature; validate scoring
76               career_pref_ui_ux_design_q077  Career preference        Q077                       Proposed domain-preference feature; validate scoring
77               career_pref_ui_ux_design_q078  Career preference        Q078                       Proposed domain-preference feature; validate scoring
78               career_pref_ui_ux_design_q079  Career preference        Q079                       Proposed domain-preference feature; validate scoring
79               career_pref_ui_ux_design_q080  Career preference        Q080                       Proposed domain-preference feature; validate scoring
80        career_pref_business_management_q081  Career preference        Q081                       Proposed domain-preference feature; validate scoring
81        career_pref_business_management_q082  Career preference        Q082                       Proposed domain-preference feature; validate scoring
82        career_pref_business_management_q083  Career preference        Q083                       Proposed domain-preference feature; validate scoring
83        career_pref_business_management_q084  Career preference        Q084                       Proposed domain-preference feature; validate scoring
84        career_pref_business_management_q085  Career preference        Q085                       Proposed domain-preference feature; validate scoring
85                 career_pref_healthcare_q086  Career preference        Q086                       Proposed domain-preference feature; validate scoring
86                 career_pref_healthcare_q087  Career preference        Q087                       Proposed domain-preference feature; validate scoring
87                 career_pref_healthcare_q088  Career preference        Q088                       Proposed domain-preference feature; validate scoring
88                 career_pref_healthcare_q089  Career preference        Q089                       Proposed domain-preference feature; validate scoring
89                 career_pref_healthcare_q090  Career preference        Q090                       Proposed domain-preference feature; validate scoring
90         career_pref_education_research_q091  Career preference        Q091                       Proposed domain-preference feature; validate scoring
91         career_pref_education_research_q092  Career preference        Q092                       Proposed domain-preference feature; validate scoring
92         career_pref_education_research_q093  Career preference        Q093                       Proposed domain-preference feature; validate scoring
93         career_pref_education_research_q094  Career preference        Q094                       Proposed domain-preference feature; validate scoring
94         career_pref_education_research_q095  Career preference        Q095                       Proposed domain-preference feature; validate scoring
95          career_pref_digital_marketing_q096  Career preference        Q096                       Proposed domain-preference feature; validate scoring
96          career_pref_digital_marketing_q097  Career preference        Q097                       Proposed domain-preference feature; validate scoring
97          career_pref_digital_marketing_q098  Career preference        Q098                       Proposed domain-preference feature; validate scoring
98          career_pref_digital_marketing_q099  Career preference        Q099                       Proposed domain-preference feature; validate scoring
99          career_pref_digital_marketing_q100  Career preference        Q100                       Proposed domain-preference feature; validate scoring
100        career_pref_finance_accounting_q101  Career preference        Q101                       Proposed domain-preference feature; validate scoring
101        career_pref_finance_accounting_q102  Career preference        Q102                       Proposed domain-preference feature; validate scoring
102        career_pref_finance_accounting_q103  Career preference        Q103                       Proposed domain-preference feature; validate scoring
103        career_pref_finance_accounting_q104  Career preference        Q104                       Proposed domain-preference feature; validate scoring
104        career_pref_finance_accounting_q105  Career preference        Q105                       Proposed domain-preference feature; validate scoring
105    career_pref_engineering_technology_q106  Career preference        Q106                       Proposed domain-preference feature; validate scoring
106    career_pref_engineering_technology_q107  Career preference        Q107                       Proposed domain-preference feature; validate scoring
107    career_pref_engineering_technology_q108  Career preference        Q108                       Proposed domain-preference feature; validate scoring
108    career_pref_engineering_technology_q109  Career preference        Q109                       Proposed domain-preference feature; validate scoring
109    career_pref_engineering_technology_q110  Career preference        Q110                       Proposed domain-preference feature; validate scoring
110       career_pref_creative_arts_media_q111  Career preference        Q111                       Proposed domain-preference feature; validate scoring
111       career_pref_creative_arts_media_q112  Career preference        Q112                       Proposed domain-preference feature; validate scoring
112       career_pref_creative_arts_media_q113  Career preference        Q113                       Proposed domain-preference feature; validate scoring
113       career_pref_creative_arts_media_q114  Career preference        Q114                       Proposed domain-preference feature; validate scoring
114       career_pref_creative_arts_media_q115  Career preference        Q115                       Proposed domain-preference feature; validate scoring
115        career_pref_law_public_service_q116  Career preference        Q116                       Proposed domain-preference feature; validate scoring
116        career_pref_law_public_service_q117  Career preference        Q117                       Proposed domain-preference feature; validate scoring
117        career_pref_law_public_service_q118  Career preference        Q118                       Proposed domain-preference feature; validate scoring
118        career_pref_law_public_service_q119  Career preference        Q119                       Proposed domain-preference feature; validate scoring
119        career_pref_law_public_service_q120  Career preference        Q120                       Proposed domain-preference feature; validate scoring

Saved: Step_10D_Feature_Alignment_Report.csv

## Step 10E — Verify the Baseline Dataset

In [25]:
# Step 10E: Baseline dataset validation

from pathlib import Path
import pandas as pd

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")
train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")
test = pd.read_csv(BASE_DIR / "career_guidance_test.csv")
mapping = pd.read_csv(
    BASE_DIR / "Question_Mapping_All_120.csv",
    encoding="utf-8-sig"
)

core_features = [
    "interest_technology",
    "interest_data",
    "interest_problem_solving",
    "interest_creativity",
    "interest_people",
    "interest_helping",
    "aptitude_logical",
    "aptitude_numerical",
    "aptitude_verbal",
    "aptitude_spatial",
    "aptitude_critical_thinking",
    "trait_openness",
    "trait_conscientiousness",
    "trait_extraversion",
    "trait_agreeableness",
    "trait_emotional_stability",
    "skill_programming",
    "skill_data_analysis",
    "skill_research",
    "skill_communication",
    "skill_leadership"
]

target = "recommended_career_domain"

print("=" * 60)
print("BASELINE DATASET VALIDATION")
print("=" * 60)

for name, df in [
    ("Processed", processed),
    ("Training", train),
    ("Test", test)
]:
    missing = [c for c in core_features + [target] if c not in df.columns]

    print(f"\n{name} dataset")
    print("Shape:", df.shape)
    print("Missing core features/target:", missing or "None")

print("\n--- Core feature ranges in processed dataset ---")
display(
    processed[core_features].agg(["min", "max", "mean"]).T
)

print("\n--- Core feature ranges in training dataset ---")
display(
    train[core_features].agg(["min", "max", "mean"]).T
)

print("\n--- Target distribution comparison ---")
target_counts = pd.concat(
    [
        processed[target].value_counts().rename("Processed"),
        train[target].value_counts().rename("Train"),
        test[target].value_counts().rename("Test")
    ],
    axis=1
).fillna(0).astype(int)

display(target_counts)

print("\n--- Core features not directly mapped by the questionnaire ---")
mapped_features = set(mapping["Proposed_Feature"].dropna().astype(str).str.strip())

unmapped_core = sorted(set(core_features) - mapped_features)

print(unmapped_core if unmapped_core else "All core features are mapped.")

print("\n--- Duplicate rows ---")
print("Processed duplicates:", processed.duplicated().sum())
print("Training duplicates:", train.duplicated().sum())
print("Test duplicates:", test.duplicated().sum())

============================================================
BASELINE DATASET VALIDATION
============================================================

Processed dataset
Shape: (2400, 27)
Missing core features/target: None

Training dataset
Shape: (1920, 26)
Missing core features/target: None

Test dataset
Shape: (480, 26)
Missing core features/target: None

--- Core feature ranges in processed dataset ---

                                 min  max      mean
interest_technology         0.033333  1.0  0.699741
interest_data               0.000000  1.0  0.657940
interest_problem_solving    0.011111  1.0  0.702843
interest_creativity         0.000000  1.0  0.685657
interest_people             0.000000  1.0  0.708509
interest_helping            0.000000  1.0  0.601139
aptitude_logical            0.088889  1.0  0.760958
aptitude_numerical          0.122222  1.0  0.724569
aptitude_verbal             0.166667  1.0  0.700315
aptitude_spatial            0.088889  1.0  0.727620
aptitude_critical_thinking  0.111111  1.0  0.702912
trait_openness              0.166667  1.0  0.719046
trait_conscientiousness     0.222222  1.0  0.733389
trait_extraversion          0.111111  1.0  0.699875
trait_agreeableness         0.100000  1.0  0.725495
trait_emotional_stability   0.100000  1.0  0.679144
skill_programming           0.000000  1.0  0.635074
skill_data_analysis         0.000000  1.0  0.636120
skill_research              0.000000  1.0  0.576764
skill_communication         0.033333  1.0  0.725236
skill_leadership            0.000000  1.0  0.683704

--- Core feature ranges in training dataset ---

                            min   max      mean
interest_technology         1.3  10.0  7.306250
interest_data               1.0  10.0  6.939688
interest_problem_solving    1.1  10.0  7.353385
interest_creativity         1.0  10.0  7.177969
interest_people             1.0  10.0  7.407552
interest_helping            1.0  10.0  6.423490
aptitude_logical            1.8  10.0  7.851458
aptitude_numerical          2.1  10.0  7.505885
aptitude_verbal             2.5  10.0  7.266510
aptitude_spatial            2.7  10.0  7.563646
aptitude_critical_thinking  2.3  10.0  7.340729
trait_openness              3.0  10.0  7.470469
trait_conscientiousness     3.2  10.0  7.608594
trait_extraversion          2.0  10.0  7.293854
trait_agreeableness         1.9  10.0  7.532604
trait_emotional_stability   1.9  10.0  7.110833
skill_programming           1.0  10.0  6.754531
skill_data_analysis         1.0  10.0  6.723542
skill_research              1.0  10.0  6.195052
skill_communication         1.3  10.0  7.548802
skill_leadership            1.0  10.0  7.172187

--- Target distribution comparison ---

                               Processed  Train  Test
recommended_career_domain
UI/UX Design                         211    169    42
Law & Public Service                 208    166    42
Education & Research                 207    166    41
Healthcare & Life Sciences           207    166    41
Software Development                 205    164    41
Data Science & Analytics             201    161    40
Engineering & Core Technology        200    160    40
Business & Management                200    160    40
Digital Marketing                    196    157    39
Finance & Accounting                 189    151    38
Creative Arts & Media                189    151    38
Cybersecurity                        187    149    38

--- Core features not directly mapped by the questionnaire ---
['aptitude_spatial', 'aptitude_verbal', 'skill_communication', 'trait_agreeableness']

--- Duplicate rows ---
Processed duplicates: 0
Training duplicates: 0
Test duplicates: 0

## Step 10F — Verify the Feature Scale and Dataset Lineage

In [27]:
# ================================================================
# STEP 10F: SCALE AND DATASET LINEAGE VERIFICATION
# ================================================================

from pathlib import Path
import numpy as np
import pandas as pd

# ------------------------------------------------
# 1. Define dataset directory
# ------------------------------------------------

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

# ------------------------------------------------
# 2. Load datasets
# ------------------------------------------------

processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")
train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")
test = pd.read_csv(BASE_DIR / "career_guidance_test.csv")

print("Datasets loaded successfully.")
print("Processed dataset:", processed.shape)
print("Training dataset:", train.shape)
print("Testing dataset:", test.shape)

# ------------------------------------------------
# 3. Define core features and target
# ------------------------------------------------

core_features = [
    "interest_technology",
    "interest_data",
    "interest_problem_solving",
    "interest_creativity",
    "interest_people",
    "interest_helping",
    "aptitude_logical",
    "aptitude_numerical",
    "aptitude_verbal",
    "aptitude_spatial",
    "aptitude_critical_thinking",
    "trait_openness",
    "trait_conscientiousness",
    "trait_extraversion",
    "trait_agreeableness",
    "trait_emotional_stability",
    "skill_programming",
    "skill_data_analysis",
    "skill_research",
    "skill_communication",
    "skill_leadership"
]

target = "recommended_career_domain"
columns = core_features + [target]

# Check that required columns exist
for dataset_name, df in [
    ("Processed", processed),
    ("Training", train),
    ("Testing", test)
]:
    missing_columns = [col for col in columns if col not in df.columns]

    if missing_columns:
        raise ValueError(
            f"{dataset_name} dataset is missing columns: "
            f"{missing_columns}"
        )

print("\nAll required features and target columns are present.")

# ------------------------------------------------
# 4. Verify original feature scales
# ------------------------------------------------

print("\n" + "=" * 65)
print("ORIGINAL FEATURE SCALE")
print("=" * 65)

print("\nProcessed dataset feature range:")
print("Minimum:", processed[core_features].min().min())
print("Maximum:", processed[core_features].max().max())

print("\nCombined training/testing feature range:")
combined = pd.concat(
    [train[columns], test[columns]],
    ignore_index=True
)

print("Minimum:", combined[core_features].min().min())
print("Maximum:", combined[core_features].max().max())

# ------------------------------------------------
# 5. Reverse-transform processed features
# ------------------------------------------------
# Candidate transformation:
# Original scale = 1 + 9 * normalized value
#
# This converts a normalized scale of 0–1
# to a candidate scale of 1–10.

reconstructed = processed[columns].copy()

reconstructed[core_features] = (
    1 + 9 * reconstructed[core_features]
)

# ------------------------------------------------
# 6. Compare feature means
# ------------------------------------------------

print("\n" + "=" * 65)
print("FEATURE MEAN COMPARISON")
print("=" * 65)

processed_means = reconstructed[core_features].mean()
combined_means = combined[core_features].mean()

mean_comparison = pd.DataFrame({
    "Reconstructed_Processed_Mean": processed_means,
    "Combined_Train_Test_Mean": combined_means
})

mean_comparison["Absolute_Mean_Difference"] = (
    mean_comparison["Reconstructed_Processed_Mean"]
    - mean_comparison["Combined_Train_Test_Mean"]
).abs()

print(mean_comparison.round(6))

print(
    "\nMaximum absolute difference between feature means:",
    round(mean_comparison["Absolute_Mean_Difference"].max(), 6)
)

# ------------------------------------------------
# 7. Verify complete record lineage
# ------------------------------------------------

def make_fingerprints(df):
    """
    Convert each complete feature-and-target row into a tuple.
    Round feature values to six decimal places to reduce
    insignificant floating-point differences.
    """

    temp = df[columns].copy()

    temp[core_features] = temp[core_features].round(6)

    return pd.Series(
        [
            tuple(row)
            for row in temp.itertuples(
                index=False,
                name=None
            )
        ],
        dtype="object"
    )


processed_fingerprints = make_fingerprints(reconstructed)
combined_fingerprints = make_fingerprints(combined)

# Count duplicate records as well as unique records
processed_counts = processed_fingerprints.value_counts()
combined_counts = combined_fingerprints.value_counts()

all_records = processed_counts.index.union(
    combined_counts.index
)

processed_counts = processed_counts.reindex(
    all_records,
    fill_value=0
)

combined_counts = combined_counts.reindex(
    all_records,
    fill_value=0
)

same_records = processed_counts.equals(combined_counts)

mismatched_records = int(
    (processed_counts != combined_counts).sum()
)

# ------------------------------------------------
# 8. Verify target labels and row counts
# ------------------------------------------------

target_labels_match = (
    set(reconstructed[target].dropna())
    == set(combined[target].dropna())
)

row_counts_match = len(reconstructed) == len(combined)

print("\n" + "=" * 65)
print("SCALE AND DATASET LINEAGE VERIFICATION")
print("=" * 65)

print("Processed row count:", len(reconstructed))
print("Combined train/test row count:", len(combined))
print("Row counts match:", row_counts_match)

print(
    "All complete records match after transformation:",
    same_records
)

print(
    "Number of record types with mismatched counts:",
    mismatched_records
)

print("Target label sets match:", target_labels_match)

# ------------------------------------------------
# 9. Check transformed feature range
# ------------------------------------------------

print("\n" + "=" * 65)
print("TRANSFORMED FEATURE RANGE")
print("=" * 65)

transformed_min = reconstructed[core_features].min().min()
transformed_max = reconstructed[core_features].max().max()

print("Minimum:", round(transformed_min, 6))
print("Maximum:", round(transformed_max, 6))

# ------------------------------------------------
# 10. Final verification summary
# ------------------------------------------------

print("\n" + "=" * 65)
print("FINAL VERIFICATION SUMMARY")
print("=" * 65)

if (
    row_counts_match
    and same_records
    and target_labels_match
):
    print(
        "SUCCESS: The reconstructed processed dataset matches "
        "the combined training and testing records."
    )
    print(
        "The candidate reverse transformation is consistent "
        "with the observed dataset records."
    )
else:
    print(
        "VERIFICATION NOT PASSED: The datasets do not fully match."
    )
    print(
        "Investigate transformation precision, dataset versions, "
        "and row-level differences before proceeding."
    )

if (
    transformed_min >= 1 - 1e-6
    and transformed_max <= 10 + 1e-6
):
    print("Scale check: Transformed features are within 1–10.")
else:
    print(
        "Scale check: Some transformed values are outside 1–10. "
        "Investigate before using the reconstructed data."
    )

print("\nStep 10F completed.")

Datasets loaded successfully.
Processed dataset: (2400, 27)
Training dataset: (1920, 26)
Testing dataset: (480, 26)

All required features and target columns are present.

=================================================================
ORIGINAL FEATURE SCALE
=================================================================

Processed dataset feature range:
Minimum: 0.0
Maximum: 1.0

Combined training/testing feature range:
Minimum: 1.0
Maximum: 10.0

=================================================================
FEATURE MEAN COMPARISON
=================================================================
                            Reconstructed_Processed_Mean  Combined_Train_Test_Mean  Absolute_Mean_Difference
interest_technology                             7.297667                  7.297667                       0.0
interest_data                                   6.921458                  6.921458                       0.0
interest_problem_solving                        7.325583                  7.325583                       0.0
interest_creativity                             7.170917                  7.170917                       0.0
interest_people                                 7.376583                  7.376583                       0.0
interest_helping                                6.410250                  6.410250                       0.0
aptitude_logical                                7.848625                  7.848625                       0.0
aptitude_numerical                              7.521125                  7.521125                       0.0
aptitude_verbal                                 7.302833                  7.302833                       0.0
aptitude_spatial                                7.548583                  7.548583                       0.0
aptitude_critical_thinking                      7.326208                  7.326208                       0.0
trait_openness                                  7.471417                  7.471417                       0.0
trait_conscientiousness                         7.600500                  7.600500                       0.0
trait_extraversion                              7.298875                  7.298875                       0.0
trait_agreeableness                             7.529458                  7.529458                       0.0
trait_emotional_stability                       7.112292                  7.112292                       0.0
skill_programming                               6.715667                  6.715667                       0.0
skill_data_analysis                             6.725083                  6.725083                       0.0
skill_research                                  6.190875                  6.190875                       0.0
skill_communication                             7.527125                  7.527125                       0.0
skill_leadership                                7.153333                  7.153333                       0.0

Maximum absolute difference between feature means: 0.0

=================================================================
SCALE AND DATASET LINEAGE VERIFICATION
=================================================================
Processed row count: 2400
Combined train/test row count: 2400
Row counts match: True
All complete records match after transformation: True
Number of record types with mismatched counts: 0
Target label sets match: True

=================================================================
TRANSFORMED FEATURE RANGE
=================================================================
Minimum: 1.0
Maximum: 10.0

=================================================================
FINAL VERIFICATION SUMMARY
=================================================================
SUCCESS: The reconstructed processed dataset matches the combined training and testing records.
The candidate reverse transformation is consistent with the observed dataset records.
Scale check: Transformed features are within 1–10.

Step 10F completed.

## Next: Step 10G — Verify target distribution and class balance

In [28]:
# ================================================================
# STEP 10G: TARGET DISTRIBUTION AND CLASS BALANCE
# ================================================================

import pandas as pd
from pathlib import Path

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")
test = pd.read_csv(BASE_DIR / "career_guidance_test.csv")
processed = pd.read_csv(BASE_DIR / "career_guidance_processed.csv")

target = "recommended_career_domain"

# Calculate class counts and percentages
def class_distribution(df, dataset_name):
    counts = df[target].value_counts().sort_index()
    percentages = (
        df[target].value_counts(normalize=True).sort_index() * 100
    )

    return pd.DataFrame({
        "Dataset": dataset_name,
        "Count": counts,
        "Percentage": percentages.round(2)
    })

distribution = pd.concat([
    class_distribution(processed, "Processed"),
    class_distribution(train, "Training"),
    class_distribution(test, "Testing")
])

print("=" * 65)
print("CAREER DOMAIN CLASS DISTRIBUTION")
print("=" * 65)
print(distribution.to_string())

print("\nNumber of classes:")
print("Processed:", processed[target].nunique())
print("Training:", train[target].nunique())
print("Testing:", test[target].nunique())

print("\nMissing target values:")
print("Processed:", processed[target].isna().sum())
print("Training:", train[target].isna().sum())
print("Testing:", test[target].isna().sum())

print("\nSmallest training class:")
print(train[target].value_counts().min())

print("\nSmallest testing class:")
print(test[target].value_counts().min())

print("\nStep 10G completed.")

=================================================================
CAREER DOMAIN CLASS DISTRIBUTION
=================================================================
                                 Dataset  Count  Percentage
recommended_career_domain
Business & Management          Processed    200        8.33
Creative Arts & Media          Processed    189        7.88
Cybersecurity                  Processed    187        7.79
Data Science & Analytics       Processed    201        8.38
Digital Marketing              Processed    196        8.17
Education & Research           Processed    207        8.62
Engineering & Core Technology  Processed    200        8.33
Finance & Accounting           Processed    189        7.88
Healthcare & Life Sciences     Processed    207        8.62
Law & Public Service           Processed    208        8.67
Software Development           Processed    205        8.54
UI/UX Design                   Processed    211        8.79
Business & Management           Training    160        8.33
Creative Arts & Media           Training    151        7.86
Cybersecurity                   Training    149        7.76
Data Science & Analytics        Training    161        8.39
Digital Marketing               Training    157        8.18
Education & Research            Training    166        8.65
Engineering & Core Technology   Training    160        8.33
Finance & Accounting            Training    151        7.86
Healthcare & Life Sciences      Training    166        8.65
Law & Public Service            Training    166        8.65
Software Development            Training    164        8.54
UI/UX Design                    Training    169        8.80
Business & Management            Testing     40        8.33
Creative Arts & Media            Testing     38        7.92
Cybersecurity                    Testing     38        7.92
Data Science & Analytics         Testing     40        8.33
Digital Marketing                Testing     39        8.12
Education & Research             Testing     41        8.54
Engineering & Core Technology    Testing     40        8.33
Finance & Accounting             Testing     38        7.92
Healthcare & Life Sciences       Testing     41        8.54
Law & Public Service             Testing     42        8.75
Software Development             Testing     41        8.54
UI/UX Design                     Testing     42        8.75

Number of classes:
Processed: 12
Training: 12
Testing: 12

Missing target values:
Processed: 0
Training: 0
Testing: 0

Smallest training class:
149

Smallest testing class:
38

Step 10G completed.

In [29]:

# ================================================================
# STEP 10H: FEATURE QUALITY AND CORRELATION ANALYSIS
# ================================================================

from pathlib import Path
import numpy as np
import pandas as pd

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

train = pd.read_csv(BASE_DIR / "career_guidance_train.csv")

core_features = [
    "interest_technology",
    "interest_data",
    "interest_problem_solving",
    "interest_creativity",
    "interest_people",
    "interest_helping",
    "aptitude_logical",
    "aptitude_numerical",
    "aptitude_verbal",
    "aptitude_spatial",
    "aptitude_critical_thinking",
    "trait_openness",
    "trait_conscientiousness",
    "trait_extraversion",
    "trait_agreeableness",
    "trait_emotional_stability",
    "skill_programming",
    "skill_data_analysis",
    "skill_research",
    "skill_communication",
    "skill_leadership"
]

X = train[core_features]

# 1. Missing values
missing = X.isnull().sum()

# 2. Constant or near-constant features
unique_counts = X.nunique()
constant_features = unique_counts[unique_counts <= 1].index.tolist()

# 3. Feature ranges and descriptive statistics
feature_summary = X.describe().T
feature_summary["Unique_Values"] = unique_counts
feature_summary["Missing_Values"] = missing

print("=" * 65)
print("FEATURE QUALITY SUMMARY")
print("=" * 65)
print(feature_summary.round(3).to_string())

print("\nTotal missing feature values:", int(missing.sum()))
print("Constant features:", constant_features)

# 4. Check values outside the expected 1–10 range
out_of_range = (
    (X < 1) | (X > 10)
).sum()

print("\nValues outside the expected 1–10 range:")
print(out_of_range[out_of_range > 0].to_dict())

# 5. Find highly correlated feature pairs
correlation_matrix = X.corr()

upper_triangle = correlation_matrix.where(
    np.triu(
        np.ones(correlation_matrix.shape),
        k=1
    ).astype(bool)
)

high_correlations = (
    upper_triangle.stack()
    .reset_index()
)

high_correlations.columns = [
    "Feature_1",
    "Feature_2",
    "Correlation"
]

high_correlations = high_correlations[
    high_correlations["Correlation"].abs() >= 0.85
].sort_values(
    by="Correlation",
    key=lambda s: s.abs(),
    ascending=False
)

print("\n" + "=" * 65)
print("HIGHLY CORRELATED FEATURE PAIRS (|r| >= 0.85)")
print("=" * 65)

if high_correlations.empty:
    print("No feature pairs crossed the 0.85 correlation threshold.")
else:
    print(high_correlations.round(3).to_string(index=False))

print("\nStep 10H completed.")

=================================================================
FEATURE QUALITY SUMMARY
=================================================================
                             count   mean    std  min  25%   50%  75%   max  Unique_Values  Missing_Values
interest_technology         1920.0  7.306  1.705  1.3  6.1  7.30  8.6  10.0             80               0
interest_data               1920.0  6.940  1.947  1.0  5.6  7.00  8.4  10.0             85               0
interest_problem_solving    1920.0  7.353  1.671  1.1  6.2  7.30  8.6  10.0             77               0
interest_creativity         1920.0  7.178  1.924  1.0  5.8  7.10  8.8  10.0             83               0
interest_people             1920.0  7.408  1.804  1.0  6.1  7.60  8.8  10.0             78               0
interest_helping            1920.0  6.423  2.042  1.0  5.0  6.40  7.9  10.0             90               0
aptitude_logical            1920.0  7.851  1.510  1.8  6.8  7.90  9.1  10.0             71               0
aptitude_numerical          1920.0  7.506  1.677  2.1  6.4  7.60  8.8  10.0             76               0
aptitude_verbal             1920.0  7.267  1.538  2.5  6.2  7.25  8.4  10.0             76               0
aptitude_spatial            1920.0  7.564  1.472  2.7  6.6  7.60  8.6  10.0             70               0
aptitude_critical_thinking  1920.0  7.341  1.536  2.3  6.3  7.40  8.5  10.0             73               0
trait_openness              1920.0  7.470  1.432  3.0  6.5  7.50  8.5  10.0             67               0
trait_conscientiousness     1920.0  7.609  1.413  3.2  6.6  7.60  8.7  10.0             68               0
trait_extraversion          1920.0  7.294  1.670  2.0  6.1  7.40  8.6  10.0             78               0
trait_agreeableness         1920.0  7.533  1.449  1.9  6.6  7.60  8.6  10.0             73               0
trait_emotional_stability   1920.0  7.111  1.578  1.9  6.1  7.10  8.2  10.0             77               0
skill_programming           1920.0  6.755  1.760  1.0  5.6  6.80  8.0  10.0             83               0
skill_data_analysis         1920.0  6.724  1.975  1.0  5.4  6.70  8.2  10.0             88               0
skill_research              1920.0  6.195  1.855  1.0  4.9  6.10  7.5  10.0             89               0
skill_communication         1920.0  7.549  1.819  1.3  6.3  7.70  9.1  10.0             78               0
skill_leadership            1920.0  7.172  2.011  1.0  5.8  7.30  8.8  10.0             87               0

Total missing feature values: 0
Constant features: []

Values outside the expected 1–10 range:
{}

=================================================================
HIGHLY CORRELATED FEATURE PAIRS (|r| >= 0.85)
=================================================================
No feature pairs crossed the 0.85 correlation threshold.

Step 10H completed.

In [30]:

# ================================================================
# STEP 10J: COMPLETE DATASET FEATURE CONSISTENCY AUDIT
# ================================================================

from pathlib import Path
import numpy as np
import pandas as pd

BASE_DIR = Path(
    r"C:\B-TECH\ACADEMIC\MLLAB\ML_PROJECT"
    r"\AI_Career_Guidance_Dataset_Package"
    r"\AI_Career_Guidance_Dataset"
)

FILES = {
    "Raw": "career_guidance_raw_synthetic.csv",
    "Processed": "career_guidance_processed.csv",
    "Training": "career_guidance_train.csv",
    "Testing": "career_guidance_test.csv"
}

TARGET = "recommended_career_domain"
ID_COLUMNS = ["profile_id"]

# ------------------------------------------------
# 1. Load all datasets
# ------------------------------------------------

datasets = {
    name: pd.read_csv(BASE_DIR / filename)
    for name, filename in FILES.items()
}

print("=" * 75)
print("STEP 10J: COMPLETE DATASET FEATURE CONSISTENCY AUDIT")
print("=" * 75)

for name, df in datasets.items():
    print(f"{name:12s}: {df.shape[0]} rows, {df.shape[1]} columns")

# ------------------------------------------------
# 2. Compare column names and schemas
# ------------------------------------------------

print("\n" + "=" * 75)
print("COLUMN SCHEMA COMPARISON")
print("=" * 75)

all_columns = set().union(
    *(set(df.columns) for df in datasets.values())
)

schema_rows = []

for column in sorted(all_columns):
    row = {"Column": column}

    for name, df in datasets.items():
        row[f"{name}_Present"] = column in df.columns

    schema_rows.append(row)

schema_report = pd.DataFrame(schema_rows)

print(schema_report.to_string(index=False))

reference_columns = set(datasets["Processed"].columns)

for name, df in datasets.items():
    missing = sorted(reference_columns - set(df.columns))
    extra = sorted(set(df.columns) - reference_columns)

    print(f"\n{name} compared with Processed:")
    print("Missing columns:", missing)
    print("Extra columns:", extra)

# ------------------------------------------------
# 3. Check duplicate column names
# ------------------------------------------------

print("\n" + "=" * 75)
print("DUPLICATE COLUMN NAME CHECK")
print("=" * 75)

for name, df in datasets.items():
    duplicates = df.columns[df.columns.duplicated()].tolist()
    print(f"{name}: {duplicates if duplicates else 'None'}")

# ------------------------------------------------
# 4. Check data types for common columns
# ------------------------------------------------

print("\n" + "=" * 75)
print("COMMON COLUMN DATA TYPE CHECK")
print("=" * 75)

common_columns = set.intersection(
    *(set(df.columns) for df in datasets.values())
)

dtype_rows = []

for column in sorted(common_columns):
    row = {"Column": column}

    for name, df in datasets.items():
        row[name] = str(df[column].dtype)

    dtype_rows.append(row)

dtype_report = pd.DataFrame(dtype_rows)
print(dtype_report.to_string(index=False))

# ------------------------------------------------
# 5. Check missing values and duplicate rows
# ------------------------------------------------

print("\n" + "=" * 75)
print("MISSING VALUES AND DUPLICATE ROWS")
print("=" * 75)

for name, df in datasets.items():
    print(f"\n{name}:")
    print("Total missing cells:", int(df.isna().sum().sum()))
    print("Columns containing missing values:",
          df.columns[df.isna().any()].tolist())
    print("Duplicate complete rows:", int(df.duplicated().sum()))

# ------------------------------------------------
# 6. Check target labels across all datasets
# ------------------------------------------------

print("\n" + "=" * 75)
print("TARGET LABEL CONSISTENCY")
print("=" * 75)

for name, df in datasets.items():
    if TARGET not in df.columns:
        print(f"{name}: TARGET COLUMN MISSING")
        continue

    print(f"\n{name}:")
    print("Missing targets:", int(df[TARGET].isna().sum()))
    print("Number of target classes:", df[TARGET].nunique())
    print("Target classes:")
    print(sorted(df[TARGET].dropna().unique()))

target_sets = {
    name: set(df[TARGET].dropna().unique())
    for name, df in datasets.items()
    if TARGET in df.columns
}

if target_sets:
    common_target_labels = set.intersection(*target_sets.values())
    all_target_labels = set.union(*target_sets.values())

    print("\nTarget labels shared by every dataset:",
          len(common_target_labels))
    print("Total distinct labels across datasets:",
          len(all_target_labels))
    print("Target label sets identical:",
          all(s == all_target_labels for s in target_sets.values()))

# ------------------------------------------------
# 7. Check expected core feature availability
# ------------------------------------------------

core_features = [
    "interest_technology",
    "interest_data",
    "interest_problem_solving",
    "interest_creativity",
    "interest_people",
    "interest_helping",
    "aptitude_logical",
    "aptitude_numerical",
    "aptitude_verbal",
    "aptitude_spatial",
    "aptitude_critical_thinking",
    "trait_openness",
    "trait_conscientiousness",
    "trait_extraversion",
    "trait_agreeableness",
    "trait_emotional_stability",
    "skill_programming",
    "skill_data_analysis",
    "skill_research",
    "skill_communication",
    "skill_leadership"
]

print("\n" + "=" * 75)
print("CORE FEATURE AVAILABILITY")
print("=" * 75)

for name, df in datasets.items():
    missing_features = [
        col for col in core_features if col not in df.columns
    ]

    print(f"{name}:")
    print("Available core features:",
          len(core_features) - len(missing_features), "/", len(core_features))
    print("Missing core features:",
          missing_features if missing_features else "None")

# ------------------------------------------------
# 8. Compare feature ranges without modifying data
# ------------------------------------------------

print("\n" + "=" * 75)
print("CORE FEATURE SCALE COMPARISON")
print("=" * 75)

for name, df in datasets.items():
    available = [
        col for col in core_features if col in df.columns
    ]

    numeric = df[available].select_dtypes(include="number")

    if numeric.empty:
        print(f"{name}: No numeric core features found.")
        continue

    print(f"\n{name}:")
    print("Minimum:", numeric.min().min())
    print("Maximum:", numeric.max().max())
    print("Feature columns outside 1–10:",
          numeric.columns[
              ((numeric < 1) | (numeric > 10)).any()
          ].tolist())

# ------------------------------------------------
# 9. Verify train/test feature schema
# ------------------------------------------------

print("\n" + "=" * 75)
print("TRAINING AND TESTING SCHEMA CHECK")
print("=" * 75)

train = datasets["Training"]
test = datasets["Testing"]

train_columns = set(train.columns)
test_columns = set(test.columns)

print("Same column names:", train_columns == test_columns)
print("Columns only in training:",
      sorted(train_columns - test_columns))
print("Columns only in testing:",
      sorted(test_columns - train_columns))

print("Same column order:",
      list(train.columns) == list(test.columns))

print("Training rows + testing rows:",
      len(train) + len(test))

print("Processed row count:",
      len(datasets["Processed"]))

print("Row counts consistent:",
      len(train) + len(test) == len(datasets["Processed"]))

# ------------------------------------------------
# 10. Save audit reports
# ------------------------------------------------

schema_report.to_csv(
    BASE_DIR / "Step_10J_Dataset_Schema_Audit.csv",
    index=False
)

dtype_report.to_csv(
    BASE_DIR / "Step_10J_Dataset_Dtype_Audit.csv",
    index=False
)

print("\nAudit reports saved:")
print("Step_10J_Dataset_Schema_Audit.csv")
print("Step_10J_Dataset_Dtype_Audit.csv")

print("\nStep 10J completed.")

===========================================================================
STEP 10J: COMPLETE DATASET FEATURE CONSISTENCY AUDIT
===========================================================================
Raw         : 2412 rows, 27 columns
Processed   : 2400 rows, 27 columns
Training    : 1920 rows, 26 columns
Testing     : 480 rows, 26 columns

===========================================================================
COLUMN SCHEMA COMPARISON
===========================================================================
                    Column  Raw_Present  Processed_Present  Training_Present  Testing_Present
                 age_group         True               True              True             True
aptitude_critical_thinking         True               True              True             True
          aptitude_logical         True               True              True             True
        aptitude_numerical         True               True              True             True
          aptitude_spatial         True               True              True             True
           aptitude_verbal         True               True              True             True
           education_level         True               True              True             True
          experience_stage         True               True              True             True
       interest_creativity         True               True              True             True
             interest_data         True               True              True             True
          interest_helping         True               True              True             True
           interest_people         True               True              True             True
  interest_problem_solving         True               True              True             True
       interest_technology         True               True              True             True
                profile_id         True               True             False            False
 recommended_career_domain         True               True              True             True
               region_type         True               True              True             True
       skill_communication         True               True              True             True
       skill_data_analysis         True               True              True             True
          skill_leadership         True               True              True             True
         skill_programming         True               True              True             True
            skill_research         True               True              True             True
       trait_agreeableness         True               True              True             True
   trait_conscientiousness         True               True              True             True
 trait_emotional_stability         True               True              True             True
        trait_extraversion         True               True              True             True
            trait_openness         True               True              True             True

Raw compared with Processed:
Missing columns: []
Extra columns: []

Processed compared with Processed:
Missing columns: []
Extra columns: []

Training compared with Processed:
Missing columns: ['profile_id']
Extra columns: []

Testing compared with Processed:
Missing columns: ['profile_id']
Extra columns: []

===========================================================================
DUPLICATE COLUMN NAME CHECK
===========================================================================
Raw: None
Processed: None
Training: None
Testing: None

===========================================================================
COMMON COLUMN DATA TYPE CHECK
===========================================================================
                    Column     Raw Processed Training Testing
                 age_group     str       str      str     str
aptitude_critical_thinking float64   float64  float64 float64
          aptitude_logical float64   float64  float64 float64
        aptitude_numerical float64   float64  float64 float64
          aptitude_spatial float64   float64  float64 float64
           aptitude_verbal float64   float64  float64 float64
           education_level     str       str      str     str
          experience_stage     str       str      str     str
       interest_creativity float64   float64  float64 float64
             interest_data float64   float64  float64 float64
          interest_helping float64   float64  float64 float64
           interest_people float64   float64  float64 float64
  interest_problem_solving float64   float64  float64 float64
       interest_technology float64   float64  float64 float64
 recommended_career_domain     str       str      str     str
               region_type     str       str      str     str
       skill_communication float64   float64  float64 float64
       skill_data_analysis float64   float64  float64 float64
          skill_leadership float64   float64  float64 float64
         skill_programming float64   float64  float64 float64
            skill_research float64   float64  float64 float64
       trait_agreeableness float64   float64  float64 float64
   trait_conscientiousness float64   float64  float64 float64
 trait_emotional_stability float64   float64  float64 float64
        trait_extraversion float64   float64  float64 float64
            trait_openness float64   float64  float64 float64

===========================================================================
MISSING VALUES AND DUPLICATE ROWS
===========================================================================

Raw:
Total missing cells: 72
Columns containing missing values: ['aptitude_logical', 'aptitude_numerical', 'trait_conscientiousness', 'trait_extraversion']
Duplicate complete rows: 12

Processed:
Total missing cells: 0
Columns containing missing values: []
Duplicate complete rows: 0

Training:
Total missing cells: 0
Columns containing missing values: []
Duplicate complete rows: 0

Testing:
Total missing cells: 0
Columns containing missing values: []
Duplicate complete rows: 0

===========================================================================
TARGET LABEL CONSISTENCY
===========================================================================

Raw:
Missing targets: 0
Number of target classes: 12
Target classes:
['Business & Management', 'Creative Arts & Media', 'Cybersecurity', 'Data Science & Analytics', 'Digital Marketing', 'Education & Research', 'Engineering & Core Technology', 'Finance & Accounting', 'Healthcare & Life Sciences', 'Law & Public Service', 'Software Development', 'UI/UX Design']

Processed:
Missing targets: 0
Number of target classes: 12
Target classes:
['Business & Management', 'Creative Arts & Media', 'Cybersecurity', 'Data Science & Analytics', 'Digital Marketing', 'Education & Research', 'Engineering & Core Technology', 'Finance & Accounting', 'Healthcare & Life Sciences', 'Law & Public Service', 'Software Development', 'UI/UX Design']

Training:
Missing targets: 0
Number of target classes: 12
Target classes:
['Business & Management', 'Creative Arts & Media', 'Cybersecurity', 'Data Science & Analytics', 'Digital Marketing', 'Education & Research', 'Engineering & Core Technology', 'Finance & Accounting', 'Healthcare & Life Sciences', 'Law & Public Service', 'Software Development', 'UI/UX Design']

Testing:
Missing targets: 0
Number of target classes: 12
Target classes:
['Business & Management', 'Creative Arts & Media', 'Cybersecurity', 'Data Science & Analytics', 'Digital Marketing', 'Education & Research', 'Engineering & Core Technology', 'Finance & Accounting', 'Healthcare & Life Sciences', 'Law & Public Service', 'Software Development', 'UI/UX Design']

Target labels shared by every dataset: 12
Total distinct labels across datasets: 12
Target label sets identical: True

===========================================================================
CORE FEATURE AVAILABILITY
===========================================================================
Raw:
Available core features: 21 / 21
Missing core features: None
Processed:
Available core features: 21 / 21
Missing core features: None
Training:
Available core features: 21 / 21
Missing core features: None
Testing:
Available core features: 21 / 21
Missing core features: None

===========================================================================
CORE FEATURE SCALE COMPARISON
===========================================================================

Raw:
Minimum: 1.0
Maximum: 10.0
Feature columns outside 1–10: []

Processed:
Minimum: 0.0
Maximum: 1.0
Feature columns outside 1–10: ['interest_technology', 'interest_data', 'interest_problem_solving', 'interest_creativity', 'interest_people', 'interest_helping', 'aptitude_logical', 'aptitude_numerical', 'aptitude_verbal', 'aptitude_spatial', 'aptitude_critical_thinking', 'trait_openness', 'trait_conscientiousness', 'trait_extraversion', 'trait_agreeableness', 'trait_emotional_stability', 'skill_programming', 'skill_data_analysis', 'skill_research', 'skill_communication', 'skill_leadership']

Training:
Minimum: 1.0
Maximum: 10.0
Feature columns outside 1–10: []

Testing:
Minimum: 1.0
Maximum: 10.0
Feature columns outside 1–10: []

===========================================================================
TRAINING AND TESTING SCHEMA CHECK
===========================================================================
Same column names: True
Columns only in training: []
Columns only in testing: []
Same column order: True
Training rows + testing rows: 2400
Processed row count: 2400
Row counts consistent: True

Audit reports saved:
Step_10J_Dataset_Schema_Audit.csv
Step_10J_Dataset_Dtype_Audit.csv

Step 10J completed.